import {
  FiBell,
  FiBookOpen,
  FiBox,
  FiBriefcase,
  FiCalendar,
  FiChevronRight,
  FiGift,
  FiGrid,
  FiHeart,
  FiHome,
  FiLayers,
  FiList,
  FiMessageSquare,
  FiPieChart,
  FiFileText,
  FiRepeat,
  FiSettings,
  FiShield,
  FiShoppingBag,
  FiUser,
  FiUsers,
} from 'react-icons/fi'
import { HiOutlineBuildingOffice2 } from 'react-icons/hi2'

export const routePreloaders = {
  '/admin': () => import('../pages/AdminPage'),
  '/moderation': () => import('../pages/ModerationPage'),
  '/activities': () => import('../pages/ActivitiesPage'),
  '/businesses': () => import('../pages/BusinessesPage'),
  '/professional': () => import('../pages/ProfessionalPage'),
  '/dashboard': () => import('../pages/DashboardPage'),
  '/moxt': () => import('../pages/MoxtHubPage'),
  '/documents': () => import('../pages/DocumentsPage'),
  '/events': () => import('../pages/EventsPage'),
  '/guide': () => import('../pages/HelpGuidePage'),
  '/favorites': () => import('../pages/FavoritesPage'),
  '/referral': () => import('../pages/ReferralPage'),
  '/feature-matrix': () => import('../pages/FeatureMatrixPage'),
  '/exchangers': () => import('../pages/ExchangersPage'),
  '/jobs': () => import('../pages/JobsPage'),
  '/jobs/applications': () => import('../pages/JobApplicationsPage'),
  '/local-data': () => import('../pages/LocalDataPage'),
  '/news': () => import('../pages/NewsPage'),
  '/marketplace': () => import('../pages/MarketplacePage'),
  '/publications/mine': () => import('../pages/MyPublicationsPage'),
  '/marketplace/mine': () => import('../pages/MyListingsPage'),
  '/messages': () => import('../pages/MessagesPage'),
  '/notifications': () => import('../pages/NotificationsPage'),
  '/p2p': () => import('../pages/P2PPage'),
  '/p2p/publish': () => import('../pages/PublishP2PPage'),
  '/payments': () => import('../pages/PaymentsPage'),
  '/parcels': () => import('../pages/ParcelsPage'),
  '/profile': () => import('../pages/ProfilePage'),
  '/profile/information': () => import('../pages/PersonalInformationPage'),
  '/receipts': () => import('../pages/ReceiptsPage'),
  '/support': () => import('../pages/SupportPage'),
  '/superadmin': () => import('../pages/SuperAdminPage'),
  '/settings': () => import('../pages/SettingsPage'),
  '/subscriptions': () => import('../pages/SubscriptionsPage'),
  '/security': () => import('../pages/SecurityPage'),
  '/transfers': () => import('../pages/NewTransferPage'),
  '/transfers/history': () => import('../pages/TransfersPage'),
  '/verification': () => import('../pages/VerificationPage'),
  '/wallet': () => import('../pages/WalletPage'),
  '/disputes': () => import('../pages/DisputesPage'),
}

export function preloadRoute(path) {
  return routePreloaders[path]?.()
}

export const navigationGroups = [
  {
    id: 'home',
    label: 'Accueil',
    labelKey: 'nav.home',
    icon: FiGrid,
    color: 'from-sky-500 to-blue-600',
    children: [
      { id: 'moxt', label: 'MOXT', labelKey: 'nav.moxt', path: '/moxt', icon: FiLayers },
      { id: 'dashboard', label: 'Accueil', labelKey: 'nav.home', path: '/dashboard', icon: FiHome },
    ],
  },
  {
    id: 'finance',
    label: 'Finances',
    labelKey: 'nav.finances',
    icon: FiRepeat,
    color: 'from-emerald-500 to-teal-500',
    children: [
      { id: 'transfers', label: 'Transfert', labelKey: 'nav.transfer', path: '/transfers', icon: FiRepeat },
      { id: 'p2p', label: 'Echanges P2P', labelKey: 'nav.p2p', path: '/p2p', icon: FiUsers },
      { id: 'exchangers', label: 'Échangeurs', labelKey: 'nav.exchangers', path: '/exchangers', icon: FiRepeat },
    ],
  },
  {
    id: 'services',
    label: 'Services',
    labelKey: 'nav.services',
    icon: FiShoppingBag,
    color: 'from-violet-500 to-purple-500',
    children: [
      {
        id: 'businesses',
        label: 'Entreprises',
        labelKey: 'nav.businesses',
        path: '/businesses',
        icon: HiOutlineBuildingOffice2,
      },
      {
        id: 'professional',
        label: 'Mon entreprise',
        labelKey: 'nav.professional',
        path: '/professional',
        icon: FiGrid,
      },
      { id: 'parcels', label: 'Colis', labelKey: 'nav.parcels', path: '/parcels', icon: FiBox },
      {
        id: 'marketplace',
        label: 'Marketplace',
        labelKey: 'nav.marketplace',
        path: '/marketplace',
        icon: FiShoppingBag,
      },
    ],
  },
  {
    id: 'community',
    label: 'Communauté',
    labelKey: 'nav.community',
    icon: FiUsers,
    color: 'from-amber-500 to-orange-500',
    children: [
      { id: 'news', label: 'Actualités', labelKey: 'nav.news', path: '/news', icon: FiFileText },
      { id: 'jobs', label: 'Jobs', labelKey: 'nav.jobs', path: '/jobs', icon: FiBriefcase },
      { id: 'events', label: 'Evenements', labelKey: 'nav.events', path: '/events', icon: FiCalendar },
      { id: 'guide', label: 'Guide', labelKey: 'nav.guide', path: '/guide', icon: FiBookOpen },
    ],
  },
  {
    id: 'communication',
    label: 'Communication',
    labelKey: 'nav.communication',
    icon: FiMessageSquare,
    color: 'from-rose-500 to-pink-500',
    children: [
      {
        id: 'messages',
        label: 'Messagerie',
        labelKey: 'nav.messages',
        path: '/messages',
        icon: FiMessageSquare,
        badgeSelector: 'messages',
      },
      {
        id: 'notifications',
        label: 'Notifications',
        labelKey: 'nav.notifications',
        path: '/notifications',
        icon: FiBell,
        badgeSelector: 'notifications',
      },
    ],
  },
  {
    id: 'account',
    label: 'Compte',
    labelKey: 'nav.account',
    icon: FiUser,
    color: 'from-slate-500 to-slate-700',
    children: [
      { id: 'profile', label: 'Profil', labelKey: 'nav.profile', path: '/profile', icon: FiUser },
      {
        id: 'subscriptions',
        label: 'Abonnements',
        labelKey: 'nav.subscriptions',
        path: '/subscriptions',
        icon: FiBell,
      },
      {
        id: 'favorites',
        label: 'Mes favoris',
        labelKey: 'nav.favorites',
        path: '/favorites',
        icon: FiHeart,
      },
      {
        id: 'referral',
        label: 'QR & invitation',
        labelKey: 'nav.qrInvitation',
        path: '/referral',
        icon: FiGift,
      },
      {
        id: 'my-publications',
        label: 'Mes publications',
        labelKey: 'nav.myPublications',
        path: '/publications/mine',
        icon: FiList,
      },
    ],
  },
  {
    id: 'moderation',
    label: 'Modération',
    labelKey: 'nav.moderation',
    icon: FiShield,
    color: 'from-cyan-500 to-teal-600',
    roles: ['moderator', 'admin', 'superadmin'],
    children: [
      {
        id: 'moderation-space',
        label: 'Espace modérateur',
        labelKey: 'nav.moderationSpace',
        path: '/moderation',
        icon: FiShield,
        roles: ['moderator', 'admin', 'superadmin'],
      },
    ],
  },
  {
    id: 'administration',
    label: 'Administration',
    labelKey: 'nav.administration',
    icon: FiSettings,
    color: 'from-red-500 to-rose-600',
    roles: ['admin', 'superadmin'],
    children: [
      {
        id: 'admin',
        label: 'Centre de contrôle',
        labelKey: 'nav.controlCenter',
        path: '/admin',
        icon: FiSettings,
        roles: ['admin', 'superadmin'],
      },
      {
        id: 'feature-matrix',
        label: 'Couverture fonctionnelle',
        path: '/feature-matrix',
        icon: FiPieChart,
        roles: ['admin', 'superadmin'],
      },
      {
        id: 'superadmin',
        label: 'Pilotage système',
        labelKey: 'nav.systemPilotage',
        path: '/superadmin',
        icon: FiShield,
        roles: ['superadmin'],
      },
    ],
  },
]

export { FiChevronRight }
