/**
 * Principales villes russes avec noms français / anglais (API) / russe.
 * Le champ `en` correspond exactement au nom retourné par countriesnow.space.
 * Le champ `nearby` liste les villes proches telles que l'API les retourne.
 */
export const MAIN_RUSSIAN_CITIES = [
  {
    id: 'moscow',
    fr: 'Moscou',
    en: 'Moscow',
    ru: 'Москва',
    region: 'Moscou (ville fédérale)',
    priority: 1,
    nearby: [
      'Khimki', 'Mytishchi', 'Balashikha', 'Podolsk', 'Lyubertsy',
      'Krasnogorsk', 'Zelenograd', 'Elektrostal', 'Korolyov', 'Reutov',
    ],
  },
  {
    id: 'spb',
    fr: 'Saint-Pétersbourg',
    en: 'Saint Petersburg',
    ru: 'Санкт-Петербург',
    region: 'Saint-Pétersbourg (ville fédérale)',
    priority: 2,
    nearby: ['Kolpino', 'Pushkin', 'Peterhof', 'Gatchina', 'Vsevolozhsk', 'Murino', 'Sertolovo'],
  },
  {
    id: 'novosibirsk',
    fr: 'Novossibirsk',
    en: 'Novosibirsk',
    ru: 'Новосибирск',
    region: 'Sibérie Occidentale',
    priority: 3,
    nearby: ['Berdsk', 'Iskitim', 'Ob'],
  },
  {
    id: 'yekaterinburg',
    fr: 'Ekaterinbourg',
    en: 'Yekaterinburg',
    ru: 'Екатеринбург',
    region: 'Oural',
    priority: 4,
    nearby: ['Pervouralsk', 'Berezovsky', 'Aramil', 'Verkhnyaya Pyshma'],
  },
  {
    id: 'kazan',
    fr: 'Kazan',
    en: 'Kazan',
    ru: 'Казань',
    region: 'Tatarstan',
    priority: 5,
    nearby: ['Zelenodolsk', 'Nizhnekamsk', 'Naberezhnye Chelny', 'Yelabuga', 'Elabuga'],
  },
  {
    id: 'nizhny_novgorod',
    fr: 'Nijni Novgorod',
    en: 'Nizhny Novgorod',
    ru: 'Нижний Новгород',
    region: 'Volga',
    priority: 6,
    nearby: ['Dzerzhinsk', 'Bor', 'Arzamas'],
  },
  {
    id: 'chelyabinsk',
    fr: 'Tcheliabinsk',
    en: 'Chelyabinsk',
    ru: 'Челябинск',
    region: 'Oural',
    priority: 7,
    nearby: ['Kopeysk', 'Magnitogorsk', 'Zlatoust'],
  },
  {
    id: 'omsk',
    fr: 'Omsk',
    en: 'Omsk',
    ru: 'Омск',
    region: 'Sibérie Occidentale',
    priority: 8,
    nearby: [],
  },
  {
    id: 'samara',
    fr: 'Samara',
    en: 'Samara',
    ru: 'Самара',
    region: 'Volga',
    priority: 9,
    nearby: ['Togliatti', 'Novokuibyshevsk', 'Chapayevsk'],
  },
  {
    id: 'rostov',
    fr: 'Rostov-sur-le-Don',
    en: 'Rostov-on-Don',
    ru: 'Ростов-на-Дону',
    region: 'Sud de la Russie',
    priority: 10,
    nearby: ['Bataysk', 'Taganrog', 'Novocherkassk', 'Aksay'],
  },
  {
    id: 'ufa',
    fr: 'Oufa',
    en: 'Ufa',
    ru: 'Уфа',
    region: 'Bachkirie',
    priority: 11,
    nearby: ['Sterlitamak', 'Salavat', 'Oktyabrsky'],
  },
  {
    id: 'krasnoyarsk',
    fr: 'Krasnoïarsk',
    en: 'Krasnoyarsk',
    ru: 'Красноярск',
    region: 'Sibérie',
    priority: 12,
    nearby: ['Divnogorsk', 'Zelenogorsk', 'Sosnovoborsk'],
  },
  {
    id: 'perm',
    fr: 'Perm',
    en: 'Perm',
    ru: 'Пермь',
    region: 'Oural',
    priority: 13,
    nearby: ['Berezniki', 'Solikamsk', 'Chaikovsky'],
  },
  {
    id: 'volgograd',
    fr: 'Volgograd',
    en: 'Volgograd',
    ru: 'Волгоград',
    region: 'Volga',
    priority: 14,
    nearby: ['Volzhsky', 'Kamyshin'],
  },
  {
    id: 'voronezh',
    fr: 'Voronej',
    en: 'Voronezh',
    ru: 'Воронеж',
    region: 'Centre',
    priority: 15,
    nearby: ['Liski', 'Borisoglebsk'],
  },
  {
    id: 'yaroslavl',
    fr: 'Iaroslavl',
    en: 'Yaroslavl',
    ru: 'Ярославль',
    region: 'Oblast de Iaroslavl',
    priority: 17,
    nearby: ['Rybinsk', 'Tutayev', 'Pereslavl-Zalessky', 'Rostov'],
  },
  {
    id: 'krasnodar',
    fr: 'Krasnodar',
    en: 'Krasnodar',
    ru: 'Краснодар',
    region: 'Krasnodar Kraï',
    priority: 16,
    nearby: ['Armavir', 'Novorossiysk', 'Anapa', 'Sochi'],
  },
  {
    id: 'saratov',
    fr: 'Saratov',
    en: 'Saratov',
    ru: 'Саратов',
    region: 'Volga',
    priority: 17,
    nearby: ['Balakovo', 'Engels'],
  },
  {
    id: 'tyumen',
    fr: 'Tioumen',
    en: 'Tyumen',
    ru: 'Тюмень',
    region: 'Sibérie Occidentale',
    priority: 18,
    nearby: ['Tobolsk', 'Ishim'],
  },
  {
    id: 'izhevsk',
    fr: 'Ijevsk',
    en: 'Izhevsk',
    ru: 'Ижевск',
    region: 'Oudmourtie',
    priority: 19,
    nearby: ['Votkinsk', 'Sarapul'],
  },
  {
    id: 'barnaul',
    fr: 'Barnaoul',
    en: 'Barnaul',
    ru: 'Барнаул',
    region: 'Altaï',
    priority: 20,
    nearby: ['Biysk', 'Rubtsovsk'],
  },
  {
    id: 'ulyanovsk',
    fr: 'Oulianovsk',
    en: 'Ulyanovsk',
    ru: 'Ульяновск',
    region: 'Volga',
    priority: 21,
    nearby: ['Dimitrovgrad'],
  },
  {
    id: 'khabarovsk',
    fr: 'Khabarovsk',
    en: 'Khabarovsk',
    ru: 'Хабаровск',
    region: 'Extrême-Orient',
    priority: 22,
    nearby: ['Komsomolsk-on-Amur'],
  },
  {
    id: 'vladivostok',
    fr: 'Vladivostok',
    en: 'Vladivostok',
    ru: 'Владивосток',
    region: 'Extrême-Orient',
    priority: 23,
    nearby: ['Artyom', 'Nakhodka', 'Ussuriysk'],
  },
  {
    id: 'irkutsk',
    fr: 'Irkoutsk',
    en: 'Irkutsk',
    ru: 'Иркутск',
    region: 'Sibérie',
    priority: 24,
    nearby: ['Angarsk', 'Bratsk', 'Usolie-Sibirskoye'],
  },
  {
    id: 'makhachkala',
    fr: 'Makhatchkala',
    en: 'Makhachkala',
    ru: 'Махачкала',
    region: 'Daghestan',
    priority: 25,
    nearby: ['Derbent', 'Khasavyurt', 'Buynaksk'],
  },
  {
    id: 'sochi',
    fr: 'Sotchi',
    en: 'Sochi',
    ru: 'Сочи',
    region: 'Krasnodar Kraï',
    priority: 26,
    nearby: ['Adler', 'Lazarevskoye', 'Khosta'],
  },
  {
    id: 'togliatti',
    fr: 'Togliatti',
    en: 'Togliatti',
    ru: 'Тольятти',
    region: 'Samara Oblast',
    priority: 27,
    nearby: [],
  },
  {
    id: 'naberezhnye_chelny',
    fr: 'Naberejnye Tchelny',
    en: 'Naberezhnye Chelny',
    ru: 'Набережные Челны',
    region: 'Tatarstan',
    priority: 28,
    nearby: ['Yelabuga', 'Elabuga', 'Nizhnekamsk'],
  },
  {
    id: 'elabuga',
    fr: 'Elabouga',
    en: 'Yelabuga',
    ru: 'Елабуга',
    region: 'Tatarstan',
    priority: 33,
    nearby: ['Naberezhnye Chelny', 'Nizhnekamsk', 'Kazan'],
  },
  {
    id: 'kursk',
    fr: 'Koursk',
    en: 'Kursk',
    ru: 'Курск',
    region: 'Centre (Koursk)',
    priority: 29,
    nearby: ['Zheleznogorsk', 'Kurchatov', 'Lgov'],
  },
  {
    id: 'oryol',
    fr: 'Orel',
    en: 'Oryol',
    ru: 'Орёл',
    region: 'Centre (Orel)',
    priority: 30,
    nearby: ['Livny', 'Mtsensk'],
  },
  {
    id: 'belgorod',
    fr: 'Belgorod',
    en: 'Belgorod',
    ru: 'Белгород',
    region: 'Centre (Belgorod)',
    priority: 31,
    nearby: ['Stary Oskol', 'Gubkin', 'Shebekino'],
  },
  {
    id: 'bryansk',
    fr: 'Briansk',
    en: 'Bryansk',
    ru: 'Брянск',
    region: 'Centre (Briansk)',
    priority: 32,
    nearby: ['Klintsy', 'Novozybkov'],
  },
  // Capitals de sujets fédéraux / grandes villes souvent recherchées (absentes avant)
  {
    id: 'kaliningrad',
    fr: 'Kaliningrad',
    en: 'Kaliningrad',
    ru: 'Калининград',
    region: 'Kaliningrad',
    priority: 34,
    nearby: ['Svetlogorsk', 'Zelenogradsk', 'Baltiysk'],
  },
  {
    id: 'tula',
    fr: 'Toula',
    en: 'Tula',
    ru: 'Тула',
    region: 'Centre (Toula)',
    priority: 35,
    nearby: ['Novomoskovsk', 'Aleksin'],
  },
  {
    id: 'ryazan',
    fr: 'Riazan',
    en: 'Ryazan',
    ru: 'Рязань',
    region: 'Centre (Riazan)',
    priority: 36,
    nearby: ['Kasimov', 'Skopin'],
  },
  {
    id: 'tver',
    fr: 'Tver',
    en: 'Tver',
    ru: 'Тверь',
    region: 'Centre (Tver)',
    priority: 37,
    nearby: ['Rzhev', 'Kimry', 'Torzhok'],
  },
  {
    id: 'vladimir',
    fr: 'Vladimir',
    en: 'Vladimir',
    ru: 'Владимир',
    region: 'Centre (Vladimir)',
    priority: 38,
    nearby: ['Kovrov', 'Murom', 'Gus-Khrustalny'],
  },
  {
    id: 'ivanovo',
    fr: 'Ivanovo',
    en: 'Ivanovo',
    ru: 'Иваново',
    region: 'Centre (Ivanovo)',
    priority: 39,
    nearby: ['Kineshma', 'Shuya'],
  },
  {
    id: 'kaluga',
    fr: 'Kalouga',
    en: 'Kaluga',
    ru: 'Калуга',
    region: 'Centre (Kalouga)',
    priority: 40,
    nearby: ['Obninsk', 'Maloyaroslavets'],
  },
  {
    id: 'kostroma',
    fr: 'Kostroma',
    en: 'Kostroma',
    ru: 'Кострома',
    region: 'Centre (Kostroma)',
    priority: 41,
    nearby: [],
  },
  {
    id: 'smolensk',
    fr: 'Smolensk',
    en: 'Smolensk',
    ru: 'Смоленск',
    region: 'Centre (Smolensk)',
    priority: 42,
    nearby: ['Vyazma', 'Roslavl'],
  },
  {
    id: 'tambov',
    fr: 'Tambov',
    en: 'Tambov',
    ru: 'Тамбов',
    region: 'Centre (Tambov)',
    priority: 43,
    nearby: ['Michurinsk'],
  },
  {
    id: 'lipetsk',
    fr: 'Lipetsk',
    en: 'Lipetsk',
    ru: 'Липецк',
    region: 'Centre (Lipetsk)',
    priority: 44,
    nearby: ['Yelets'],
  },
  {
    id: 'pskov',
    fr: 'Pskov',
    en: 'Pskov',
    ru: 'Псков',
    region: 'Nord-Ouest',
    priority: 45,
    nearby: ['Velikiye Luki'],
  },
  {
    id: 'veliky_novgorod',
    fr: 'Veliki Novgorod',
    en: 'Veliky Novgorod',
    ru: 'Великий Новгород',
    region: 'Nord-Ouest',
    priority: 46,
    nearby: ['Borovichi', 'Staraya Russa'],
  },
  {
    id: 'orenburg',
    fr: 'Orenbourg',
    en: 'Orenburg',
    ru: 'Оренбург',
    region: 'Volga (Orenbourg)',
    priority: 47,
    nearby: ['Orsk', 'Novotroitsk', 'Buzuluk'],
  },
  {
    id: 'astrakhan',
    fr: 'Astrakhan',
    en: 'Astrakhan',
    ru: 'Астрахань',
    region: 'Sud (Astrakhan)',
    priority: 48,
    nearby: ['Akhtubinsk'],
  },
  {
    id: 'penza',
    fr: 'Penza',
    en: 'Penza',
    ru: 'Пенза',
    region: 'Volga (Penza)',
    priority: 49,
    nearby: ['Kuznetsk', 'Zarechny'],
  },
  {
    id: 'stavropol',
    fr: 'Stavropol',
    en: 'Stavropol',
    ru: 'Ставрополь',
    region: 'Caucase du Nord',
    priority: 50,
    nearby: ['Pyatigorsk', 'Kislovodsk', 'Nevinnomyssk', 'Essentuki'],
  },
  {
    id: 'grozny',
    fr: 'Grozny',
    en: 'Grozny',
    ru: 'Грозный',
    region: 'Tchétchénie',
    priority: 51,
    nearby: [],
  },
  {
    id: 'vladikavkaz',
    fr: 'Vladikavkaz',
    en: 'Vladikavkaz',
    ru: 'Владикавказ',
    region: 'Ossétie du Nord',
    priority: 52,
    nearby: [],
  },
  {
    id: 'nalchik',
    fr: 'Naltchik',
    en: 'Nalchik',
    ru: 'Нальчик',
    region: 'Kabardino-Balkarie',
    priority: 53,
    nearby: [],
  },
  {
    id: 'cheboksary',
    fr: 'Tcheboksary',
    en: 'Cheboksary',
    ru: 'Чебоксары',
    region: 'Tchouvachie',
    priority: 54,
    nearby: ['Novocheboksarsk'],
  },
  {
    id: 'saransk',
    fr: 'Saransk',
    en: 'Saransk',
    ru: 'Саранск',
    region: 'Mordovie',
    priority: 55,
    nearby: [],
  },
  {
    id: 'yoshkar_ola',
    fr: 'Iochkar-Ola',
    en: 'Yoshkar-Ola',
    ru: 'Йошкар-Ола',
    region: 'Mari El',
    priority: 56,
    nearby: [],
  },
  {
    id: 'arkhangelsk',
    fr: 'Arkhangelsk',
    en: 'Arkhangelsk',
    ru: 'Архангельск',
    region: 'Nord',
    priority: 57,
    nearby: ['Severodvinsk', 'Kotlas'],
  },
  {
    id: 'murmansk',
    fr: 'Mourmansk',
    en: 'Murmansk',
    ru: 'Мурманск',
    region: 'Nord',
    priority: 58,
    nearby: ['Apatity', 'Severomorsk'],
  },
  {
    id: 'petrozavodsk',
    fr: 'Petrozavodsk',
    en: 'Petrozavodsk',
    ru: 'Петрозаводск',
    region: 'Carélie',
    priority: 59,
    nearby: ['Kondopoga'],
  },
  {
    id: 'syktyvkar',
    fr: 'Syktyvkar',
    en: 'Syktyvkar',
    ru: 'Сыктывкар',
    region: 'Komi',
    priority: 60,
    nearby: ['Ukhta', 'Vorkuta'],
  },
  {
    id: 'vologda',
    fr: 'Vologda',
    en: 'Vologda',
    ru: 'Вологда',
    region: 'Nord-Ouest',
    priority: 61,
    nearby: ['Cherepovets', 'Veliky Ustyug'],
  },
  {
    id: 'cherepovets',
    fr: 'Tcherepovets',
    en: 'Cherepovets',
    ru: 'Череповец',
    region: 'Nord-Ouest',
    priority: 62,
    nearby: ['Vologda'],
  },
  {
    id: 'tomsk',
    fr: 'Tomsk',
    en: 'Tomsk',
    ru: 'Томск',
    region: 'Sibérie',
    priority: 63,
    nearby: ['Seversk', 'Strezhevoy'],
  },
  {
    id: 'kemerovo',
    fr: 'Kemerovo',
    en: 'Kemerovo',
    ru: 'Кемерово',
    region: 'Sibérie (Kouzbass)',
    priority: 64,
    nearby: ['Novokuznetsk', 'Prokopyevsk', 'Leninsk-Kuznetsky'],
  },
  {
    id: 'novokuznetsk',
    fr: 'Novokouznetsk',
    en: 'Novokuznetsk',
    ru: 'Новокузнецк',
    region: 'Sibérie (Kouzbass)',
    priority: 65,
    nearby: ['Kemerovo', 'Prokopyevsk'],
  },
  {
    id: 'surgut',
    fr: 'Sourgout',
    en: 'Surgut',
    ru: 'Сургут',
    region: 'Khantys-Mansis',
    priority: 66,
    nearby: ['Nizhnevartovsk', 'Nefteyugansk'],
  },
  {
    id: 'nizhnevartovsk',
    fr: 'Nijnevartovsk',
    en: 'Nizhnevartovsk',
    ru: 'Нижневартовск',
    region: 'Khantys-Mansis',
    priority: 67,
    nearby: ['Surgut'],
  },
  {
    id: 'yakutsk',
    fr: 'Iakoutsk',
    en: 'Yakutsk',
    ru: 'Якутск',
    region: 'Iakoutie',
    priority: 68,
    nearby: [],
  },
  {
    id: 'ulan_ude',
    fr: 'Oulan-Oudé',
    en: 'Ulan-Ude',
    ru: 'Улан-Удэ',
    region: 'Bouriatie',
    priority: 69,
    nearby: [],
  },
  {
    id: 'chita',
    fr: 'Tchita',
    en: 'Chita',
    ru: 'Чита',
    region: 'Transbaïkalie',
    priority: 70,
    nearby: [],
  },
  {
    id: 'blagoveshchensk',
    fr: 'Blagovechtchensk',
    en: 'Blagoveshchensk',
    ru: 'Благовещенск',
    region: 'Extrême-Orient (Amour)',
    priority: 71,
    nearby: [],
  },
  {
    id: 'magadan',
    fr: 'Magadan',
    en: 'Magadan',
    ru: 'Магадан',
    region: 'Extrême-Orient',
    priority: 72,
    nearby: [],
  },
  {
    id: 'petropavlovsk_kamchatsky',
    fr: 'Petropavlovsk-Kamtchatski',
    en: 'Petropavlovsk-Kamchatsky',
    ru: 'Петропавловск-Камчатский',
    region: 'Kamtchatka',
    priority: 73,
    nearby: [],
  },
  {
    id: 'yuzhno_sakhalinsk',
    fr: 'Ioujno-Sakhalinsk',
    en: 'Yuzhno-Sakhalinsk',
    ru: 'Южно-Сахалинск',
    region: 'Sakhaline',
    priority: 74,
    nearby: [],
  },
  {
    id: 'magnitogorsk',
    fr: 'Magnitogorsk',
    en: 'Magnitogorsk',
    ru: 'Магнитогорск',
    region: 'Oural',
    priority: 75,
    nearby: ['Chelyabinsk'],
  },
  {
    id: 'kurgan',
    fr: 'Kourgan',
    en: 'Kurgan',
    ru: 'Курган',
    region: 'Oural',
    priority: 76,
    nearby: [],
  },
  {
    id: 'kirov',
    fr: 'Kirov',
    en: 'Kirov',
    ru: 'Киров',
    region: 'Volga (Kirov)',
    priority: 77,
    nearby: ['Kirovo-Chepetsk'],
  },
]

/** Map: nom anglais API → nom français d'affichage */
export const EN_TO_FR = {
  ...Object.fromEntries(MAIN_RUSSIAN_CITIES.map((c) => [c.en.toLowerCase(), c.fr])),
  elabuga: 'Elabouga',
  yelabuga: 'Elabouga',
}

/** Retrouve la ville principale parente d'une ville proche */
export function findParentCity(apiCityName) {
  const needle = String(apiCityName || '').toLowerCase()
  if (!needle) return null
  return (
    MAIN_RUSSIAN_CITIES.find((m) =>
      (m.nearby || []).some((n) => n.toLowerCase() === needle),
    ) || null
  )
}

/** Convertit un nom anglais API en nom français si connu, sinon retourne tel quel */
export function toFrenchCityName(englishName) {
  if (englishName == null || englishName === '') return englishName
  return EN_TO_FR[String(englishName).toLowerCase()] ?? englishName
}
