/**
 * 28 principales villes russes avec noms français / anglais (API) / russe.
 * Le champ `en` correspond exactement au nom retourné par countriesnow.space.
 * Le champ `nearby` liste les villes proches telles que l'API les retourne.
 */
export const MAIN_RUSSIAN_CITIES = [
  {
    id: 'moscow',
    fr: 'Moscou',
    en: 'Moscow',
    ru: 'Москва',
    region: 'Moscou (ville fédérale)',
    priority: 1,
    nearby: [
      'Khimki', 'Mytishchi', 'Balashikha', 'Podolsk', 'Lyubertsy',
      'Krasnogorsk', 'Zelenograd', 'Elektrostal', 'Korolyov', 'Reutov',
    ],
  },
  {
    id: 'spb',
    fr: 'Saint-Pétersbourg',
    en: 'Saint Petersburg',
    ru: 'Санкт-Петербург',
    region: 'Saint-Pétersbourg (ville fédérale)',
    priority: 2,
    nearby: ['Kolpino', 'Pushkin', 'Peterhof', 'Gatchina', 'Vsevolozhsk', 'Murino', 'Sertolovo'],
  },
  {
    id: 'novosibirsk',
    fr: 'Novossibirsk',
    en: 'Novosibirsk',
    ru: 'Новосибирск',
    region: 'Sibérie Occidentale',
    priority: 3,
    nearby: ['Berdsk', 'Iskitim', 'Ob'],
  },
  {
    id: 'yekaterinburg',
    fr: 'Ekaterinbourg',
    en: 'Yekaterinburg',
    ru: 'Екатеринбург',
    region: 'Oural',
    priority: 4,
    nearby: ['Pervouralsk', 'Berezovsky', 'Aramil', 'Verkhnyaya Pyshma'],
  },
  {
    id: 'kazan',
    fr: 'Kazan',
    en: 'Kazan',
    ru: 'Казань',
    region: 'Tatarstan',
    priority: 5,
    nearby: ['Zelenodolsk', 'Nizhnekamsk', 'Naberezhnye Chelny'],
  },
  {
    id: 'nizhny_novgorod',
    fr: 'Nijni Novgorod',
    en: 'Nizhny Novgorod',
    ru: 'Нижний Новгород',
    region: 'Volga',
    priority: 6,
    nearby: ['Dzerzhinsk', 'Bor', 'Arzamas'],
  },
  {
    id: 'chelyabinsk',
    fr: 'Tcheliabinsk',
    en: 'Chelyabinsk',
    ru: 'Челябинск',
    region: 'Oural',
    priority: 7,
    nearby: ['Kopeysk', 'Magnitogorsk', 'Zlatoust'],
  },
  {
    id: 'omsk',
    fr: 'Omsk',
    en: 'Omsk',
    ru: 'Омск',
    region: 'Sibérie Occidentale',
    priority: 8,
    nearby: [],
  },
  {
    id: 'samara',
    fr: 'Samara',
    en: 'Samara',
    ru: 'Самара',
    region: 'Volga',
    priority: 9,
    nearby: ['Togliatti', 'Novokuibyshevsk', 'Chapayevsk'],
  },
  {
    id: 'rostov',
    fr: 'Rostov-sur-le-Don',
    en: 'Rostov-on-Don',
    ru: 'Ростов-на-Дону',
    region: 'Sud de la Russie',
    priority: 10,
    nearby: ['Bataysk', 'Taganrog', 'Novocherkassk', 'Aksay'],
  },
  {
    id: 'ufa',
    fr: 'Oufa',
    en: 'Ufa',
    ru: 'Уфа',
    region: 'Bachkirie',
    priority: 11,
    nearby: ['Sterlitamak', 'Salavat', 'Oktyabrsky'],
  },
  {
    id: 'krasnoyarsk',
    fr: 'Krasnoïarsk',
    en: 'Krasnoyarsk',
    ru: 'Красноярск',
    region: 'Sibérie',
    priority: 12,
    nearby: ['Divnogorsk', 'Zelenogorsk', 'Sosnovoborsk'],
  },
  {
    id: 'perm',
    fr: 'Perm',
    en: 'Perm',
    ru: 'Пермь',
    region: 'Oural',
    priority: 13,
    nearby: ['Berezniki', 'Solikamsk', 'Chaikovsky'],
  },
  {
    id: 'volgograd',
    fr: 'Volgograd',
    en: 'Volgograd',
    ru: 'Волгоград',
    region: 'Volga',
    priority: 14,
    nearby: ['Volzhsky', 'Kamyshin'],
  },
  {
    id: 'voronezh',
    fr: 'Voronej',
    en: 'Voronezh',
    ru: 'Воронеж',
    region: 'Centre',
    priority: 15,
    nearby: ['Liski', 'Borisoglebsk'],
  },
  {
    id: 'krasnodar',
    fr: 'Krasnodar',
    en: 'Krasnodar',
    ru: 'Краснодар',
    region: 'Krasnodar Kraï',
    priority: 16,
    nearby: ['Armavir', 'Novorossiysk', 'Anapa', 'Sochi'],
  },
  {
    id: 'saratov',
    fr: 'Saratov',
    en: 'Saratov',
    ru: 'Саратов',
    region: 'Volga',
    priority: 17,
    nearby: ['Balakovo', 'Engels'],
  },
  {
    id: 'tyumen',
    fr: 'Tioumen',
    en: 'Tyumen',
    ru: 'Тюмень',
    region: 'Sibérie Occidentale',
    priority: 18,
    nearby: ['Tobolsk', 'Ishim'],
  },
  {
    id: 'izhevsk',
    fr: 'Ijevsk',
    en: 'Izhevsk',
    ru: 'Ижевск',
    region: 'Oudmourtie',
    priority: 19,
    nearby: ['Votkinsk', 'Sarapul'],
  },
  {
    id: 'barnaul',
    fr: 'Barnaoul',
    en: 'Barnaul',
    ru: 'Барнаул',
    region: 'Altaï',
    priority: 20,
    nearby: ['Biysk', 'Rubtsovsk'],
  },
  {
    id: 'ulyanovsk',
    fr: 'Oulianovsk',
    en: 'Ulyanovsk',
    ru: 'Ульяновск',
    region: 'Volga',
    priority: 21,
    nearby: ['Dimitrovgrad'],
  },
  {
    id: 'khabarovsk',
    fr: 'Khabarovsk',
    en: 'Khabarovsk',
    ru: 'Хабаровск',
    region: 'Extrême-Orient',
    priority: 22,
    nearby: ['Komsomolsk-on-Amur'],
  },
  {
    id: 'vladivostok',
    fr: 'Vladivostok',
    en: 'Vladivostok',
    ru: 'Владивосток',
    region: 'Extrême-Orient',
    priority: 23,
    nearby: ['Artyom', 'Nakhodka', 'Ussuriysk'],
  },
  {
    id: 'irkutsk',
    fr: 'Irkoutsk',
    en: 'Irkutsk',
    ru: 'Иркутск',
    region: 'Sibérie',
    priority: 24,
    nearby: ['Angarsk', 'Bratsk', 'Usolie-Sibirskoye'],
  },
  {
    id: 'makhachkala',
    fr: 'Makhatchkala',
    en: 'Makhachkala',
    ru: 'Махачкала',
    region: 'Daghestan',
    priority: 25,
    nearby: ['Derbent', 'Khasavyurt', 'Buynaksk'],
  },
  {
    id: 'sochi',
    fr: 'Sotchi',
    en: 'Sochi',
    ru: 'Сочи',
    region: 'Krasnodar Kraï',
    priority: 26,
    nearby: ['Adler', 'Lazarevskoye', 'Khosta'],
  },
  {
    id: 'togliatti',
    fr: 'Togliatti',
    en: 'Togliatti',
    ru: 'Тольятти',
    region: 'Samara Oblast',
    priority: 27,
    nearby: [],
  },
  {
    id: 'naberezhnye_chelny',
    fr: 'Naberejnye Tchelny',
    en: 'Naberezhnye Chelny',
    ru: 'Набережные Челны',
    region: 'Tatarstan',
    priority: 28,
    nearby: [],
  },
]

/** Map: nom anglais API → nom français d'affichage */
export const EN_TO_FR = Object.fromEntries(
  MAIN_RUSSIAN_CITIES.map((c) => [c.en.toLowerCase(), c.fr]),
)

/** Retrouve la ville principale parente d'une ville proche */
export function findParentCity(apiCityName) {
  return (
    MAIN_RUSSIAN_CITIES.find((m) =>
      m.nearby.some((n) => n.toLowerCase() === apiCityName.toLowerCase()),
    ) || null
  )
}

/** Convertit un nom anglais API en nom français si connu, sinon retourne tel quel */
export function toFrenchCityName(englishName) {
  return EN_TO_FR[englishName.toLowerCase()] ?? englishName
}
