// Pages statiques de l'application (hors contenus dynamiques deja indexes par
// searchSelectors : entreprises, annonces, emplois, evenements, colis).
// Permet a la recherche globale de retrouver aussi les ecrans de compte,
// parametres et administration, pas seulement les fiches.
export const searchablePages = [
  {
    id: 'page-dashboard',
    title: 'Accueil',
    titleKey: 'shared.pages.dashboard.title',
    subtitle: 'Tableau de bienvenue',
    subtitleKey: 'shared.pages.dashboard.subtitle',
    path: '/dashboard',
    keywords: 'accueil home',
  },
  {
    id: 'page-moxt',
    title: 'MOXT',
    titleKey: 'shared.pages.moxt.title',
    subtitle: 'Tous les services',
    subtitleKey: 'shared.pages.moxt.subtitle',
    path: '/moxt',
    keywords: 'moxt services hub plateforme',
  },
  {
    id: 'page-transfers',
    title: 'Nouveau transfert',
    titleKey: 'shared.pages.transfers.title',
    subtitle: 'Finances',
    subtitleKey: 'shared.pages.groups.finances',
    path: '/transfers',
    keywords: 'envoyer argent transfert',
  },
  {
    id: 'page-transfers-history',
    title: 'Historique des transferts',
    titleKey: 'shared.pages.transfersHistory.title',
    subtitle: 'Finances',
    subtitleKey: 'shared.pages.groups.finances',
    path: '/transfers/history',
  },
  {
    id: 'page-exchangers',
    title: 'Échangeurs',
    titleKey: 'shared.pages.exchangers.title',
    subtitle: 'Finances',
    subtitleKey: 'shared.pages.groups.finances',
    path: '/exchangers',
  },
  {
    id: 'page-p2p',
    title: 'Échanges P2P',
    titleKey: 'shared.pages.p2p.title',
    subtitle: 'Finances',
    subtitleKey: 'shared.pages.groups.finances',
    path: '/p2p',
  },
  {
    id: 'page-payments',
    title: 'Paiements',
    titleKey: 'shared.pages.payments.title',
    subtitle: 'Finances',
    subtitleKey: 'shared.pages.groups.finances',
    path: '/payments',
  },
  {
    id: 'page-receipts',
    title: 'Reçus',
    titleKey: 'shared.pages.receipts.title',
    subtitle: 'Finances',
    subtitleKey: 'shared.pages.groups.finances',
    path: '/receipts',
  },
  {
    id: 'page-disputes',
    title: 'Mes litiges',
    titleKey: 'shared.pages.disputes.title',
    subtitle: 'Compte',
    subtitleKey: 'shared.pages.groups.account',
    path: '/disputes',
    keywords: 'litige reclamation probleme',
  },
  {
    id: 'page-businesses',
    title: 'Entreprises',
    titleKey: 'shared.pages.businesses.title',
    subtitle: 'Services',
    subtitleKey: 'shared.pages.groups.services',
    path: '/businesses',
  },
  {
    id: 'page-professional',
    title: 'Mon entreprise',
    titleKey: 'shared.pages.professional.title',
    subtitle: 'Services',
    subtitleKey: 'shared.pages.groups.services',
    path: '/professional',
    keywords: 'pro business',
  },
  {
    id: 'page-parcels',
    title: 'Colis',
    titleKey: 'shared.pages.parcels.title',
    subtitle: 'Services',
    subtitleKey: 'shared.pages.groups.services',
    path: '/parcels',
    keywords: 'envoi bagage transport',
  },
  {
    id: 'page-marketplace',
    title: 'Marketplace',
    titleKey: 'shared.pages.marketplace.title',
    subtitle: 'Services',
    subtitleKey: 'shared.pages.groups.services',
    path: '/marketplace',
    keywords: 'market boutique annonces',
  },
  {
    id: 'page-publications-mine',
    title: 'Mes publications',
    titleKey: 'shared.pages.myPublications.title',
    subtitle: 'Compte',
    subtitleKey: 'shared.pages.groups.account',
    path: '/publications/mine',
    keywords: 'annonces colis jobs evenements archives',
  },
  {
    id: 'page-news',
    title: 'Actualités',
    titleKey: 'shared.pages.news.title',
    subtitle: 'Communauté',
    subtitleKey: 'shared.pages.groups.community',
    path: '/news',
  },
  {
    id: 'page-jobs',
    title: 'Jobs',
    titleKey: 'shared.pages.jobs.title',
    subtitle: 'Communauté',
    subtitleKey: 'shared.pages.groups.community',
    path: '/jobs',
    keywords: 'travail job recrutement',
  },
  {
    id: 'page-events',
    title: 'Événements',
    titleKey: 'shared.pages.events.title',
    subtitle: 'Communauté',
    subtitleKey: 'shared.pages.groups.community',
    path: '/events',
  },
  {
    id: 'page-messages',
    title: 'Messagerie',
    titleKey: 'shared.pages.messages.title',
    subtitle: 'Communication',
    subtitleKey: 'shared.pages.groups.communication',
    path: '/messages',
    keywords: 'message chat conversation',
  },
  {
    id: 'page-notifications',
    title: 'Notifications',
    titleKey: 'shared.pages.notifications.title',
    subtitle: 'Communication',
    subtitleKey: 'shared.pages.groups.communication',
    path: '/notifications',
  },
  {
    id: 'page-support',
    title: 'Support',
    titleKey: 'shared.pages.support.title',
    subtitle: 'Communication',
    subtitleKey: 'shared.pages.groups.communication',
    path: '/support',
    keywords: 'aide assistance contact instagram moxtapp reseaux sociaux',
  },
  {
    id: 'page-activities',
    title: 'Mes activités',
    titleKey: 'shared.pages.activities.title',
    subtitle: 'Compte',
    subtitleKey: 'shared.pages.groups.account',
    path: '/activities',
    keywords: 'historique activite',
  },
  {
    id: 'page-favorites',
    title: 'Mes favoris',
    titleKey: 'shared.pages.favorites.title',
    subtitle: 'Compte',
    subtitleKey: 'shared.pages.groups.account',
    path: '/favorites',
    keywords: 'favori like aime',
  },
  {
    id: 'page-documents',
    title: 'Mes documents',
    titleKey: 'shared.pages.documents.title',
    subtitle: 'Compte',
    subtitleKey: 'shared.pages.groups.account',
    path: '/documents',
    keywords: 'fichier piece jointe',
  },
  {
    id: 'page-verification',
    title: 'Vérification',
    titleKey: 'shared.pages.verification.title',
    subtitle: 'Compte',
    subtitleKey: 'shared.pages.groups.account',
    path: '/verification',
    keywords: 'kyc identite verifier',
  },
  {
    id: 'page-security',
    title: 'Sécurité',
    titleKey: 'shared.pages.security.title',
    subtitle: 'Compte',
    subtitleKey: 'shared.pages.groups.account',
    path: '/security',
    keywords: 'mot de passe securite 2fa',
  },
  {
    id: 'page-profile',
    title: 'Mon profil',
    titleKey: 'shared.pages.profile.title',
    subtitle: 'Compte',
    subtitleKey: 'shared.pages.groups.account',
    path: '/profile',
    keywords: 'compte utilisateur identite',
  },
  {
    id: 'page-profile-information',
    title: 'Informations personnelles',
    titleKey: 'shared.pages.profileInformation.title',
    subtitle: 'Compte',
    subtitleKey: 'shared.pages.groups.account',
    path: '/profile/information',
    keywords: 'nom prenom email telephone adresse',
  },
  {
    id: 'page-settings',
    title: 'Paramètres',
    titleKey: 'shared.pages.settings.title',
    subtitle: 'Compte',
    subtitleKey: 'shared.pages.groups.account',
    path: '/settings',
    keywords: 'reglages preferences langue theme',
  },
  {
    id: 'page-local-data',
    title: 'Données locales',
    titleKey: 'shared.pages.localData.title',
    subtitle: 'Compte',
    subtitleKey: 'shared.pages.groups.account',
    path: '/local-data',
    keywords: 'cache stockage local',
  },
  {
    id: 'page-moderation',
    title: 'Espace modérateur',
    titleKey: 'shared.pages.moderation.title',
    subtitle: 'Modération',
    subtitleKey: 'shared.pages.groups.moderation',
    path: '/moderation',
    roles: ['moderator', 'admin', 'superadmin'],
  },
  {
    id: 'page-admin',
    title: 'Centre de contrôle',
    titleKey: 'shared.pages.admin.title',
    subtitle: 'Administration',
    subtitleKey: 'shared.pages.groups.admin',
    path: '/admin',
    roles: ['admin', 'superadmin'],
  },
  {
    id: 'page-feature-matrix',
    title: 'Couverture fonctionnelle',
    titleKey: 'shared.pages.featureMatrix.title',
    subtitle: 'Administration',
    subtitleKey: 'shared.pages.groups.admin',
    path: '/feature-matrix',
    roles: ['admin', 'superadmin'],
  },
  {
    id: 'page-superadmin',
    title: 'Pilotage système',
    titleKey: 'shared.pages.superadmin.title',
    subtitle: 'Superadmin',
    subtitleKey: 'shared.pages.groups.superadmin',
    path: '/superadmin',
    roles: ['superadmin'],
  },
]
