// Pages statiques de l'application (hors contenus dynamiques deja indexes par
// searchSelectors : entreprises, annonces, emplois, evenements, colis).
// Permet a la recherche globale de retrouver aussi les ecrans de compte,
// parametres et administration, pas seulement les fiches.
export const searchablePages = [
  { id: 'page-dashboard', title: 'Accueil', subtitle: 'Tableau de bienvenue', path: '/dashboard', keywords: 'accueil home' },
  { id: 'page-transfers', title: 'Nouveau transfert', subtitle: 'Finances', path: '/transfers', keywords: 'envoyer argent transfert' },
  { id: 'page-transfers-history', title: 'Historique des transferts', subtitle: 'Finances', path: '/transfers/history' },
  { id: 'page-exchangers', title: 'Échangeurs', subtitle: 'Finances', path: '/exchangers' },
  { id: 'page-p2p', title: 'Échanges P2P', subtitle: 'Finances', path: '/p2p' },
  { id: 'page-wallet', title: 'Portefeuille', subtitle: 'Finances', path: '/wallet', keywords: 'wallet solde' },
  { id: 'page-payments', title: 'Paiements', subtitle: 'Finances', path: '/payments' },
  { id: 'page-receipts', title: 'Reçus', subtitle: 'Finances', path: '/receipts' },
  { id: 'page-disputes', title: 'Mes litiges', subtitle: 'Compte', path: '/disputes', keywords: 'litige reclamation probleme' },
  { id: 'page-businesses', title: 'Entreprises', subtitle: 'Services', path: '/businesses' },
  { id: 'page-professional', title: 'Espace professionnel', subtitle: 'Services', path: '/professional', keywords: 'pro business' },
  { id: 'page-parcels', title: 'Colis', subtitle: 'Services', path: '/parcels', keywords: 'envoi bagage transport' },
  { id: 'page-marketplace', title: 'Marketplace', subtitle: 'Services', path: '/marketplace', keywords: 'market boutique annonces' },
  { id: 'page-marketplace-mine', title: 'Mes annonces', subtitle: 'Marketplace', path: '/marketplace/mine' },
  { id: 'page-news', title: 'Actualités', subtitle: 'Communauté', path: '/news' },
  { id: 'page-jobs', title: 'Jobs', subtitle: 'Communauté', path: '/jobs', keywords: 'travail job recrutement' },
  { id: 'page-events', title: 'Événements', subtitle: 'Communauté', path: '/events' },
  { id: 'page-messages', title: 'Messagerie', subtitle: 'Communication', path: '/messages', keywords: 'message chat conversation' },
  { id: 'page-notifications', title: 'Notifications', subtitle: 'Communication', path: '/notifications' },
  { id: 'page-support', title: 'Support', subtitle: 'Communication', path: '/support', keywords: 'aide assistance contact' },
  { id: 'page-activities', title: 'Mes activités', subtitle: 'Compte', path: '/activities', keywords: 'historique activite' },
  { id: 'page-favorites', title: 'Mes favoris', subtitle: 'Compte', path: '/favorites', keywords: 'favori like aime' },
  { id: 'page-documents', title: 'Mes documents', subtitle: 'Compte', path: '/documents', keywords: 'fichier piece jointe' },
  { id: 'page-verification', title: 'Vérification', subtitle: 'Compte', path: '/verification', keywords: 'kyc identite verifier' },
  { id: 'page-security', title: 'Sécurité', subtitle: 'Compte', path: '/security', keywords: 'mot de passe securite 2fa' },
  { id: 'page-profile', title: 'Mon profil', subtitle: 'Compte', path: '/profile', keywords: 'compte utilisateur identite' },
  {
    id: 'page-profile-information',
    title: 'Informations personnelles',
    subtitle: 'Compte',
    path: '/profile/information',
    keywords: 'nom prenom email telephone adresse',
  },
  { id: 'page-settings', title: 'Paramètres', subtitle: 'Compte', path: '/settings', keywords: 'reglages preferences langue theme' },
  { id: 'page-local-data', title: 'Données locales', subtitle: 'Compte', path: '/local-data', keywords: 'cache stockage local' },
  {
    id: 'page-admin',
    title: 'Centre de contrôle',
    subtitle: 'Administration',
    path: '/admin',
    roles: ['admin', 'superadmin'],
  },
  {
    id: 'page-feature-matrix',
    title: 'Couverture fonctionnelle',
    subtitle: 'Administration',
    path: '/feature-matrix',
    roles: ['admin', 'superadmin'],
  },
  {
    id: 'page-superadmin',
    title: 'Pilotage système',
    subtitle: 'Superadmin',
    path: '/superadmin',
    roles: ['superadmin'],
  },
]
