export const ROUTES = {
  dashboard: '/dashboard',
  profile: '/profile',
  profileInformation: '/profile/information',
  activities: '/activities',
  favorites: '/favorites',
  subscriptions: '/subscriptions',
  documents: '/documents',
  verification: '/verification',
  security: '/security',
  settings: '/settings',
  localData: '/local-data',
  news: '/news',
  transfers: '/transfers',
  transferHistory: '/transfers/history',
  exchangers: '/exchangers',
  receipts: '/receipts',
  disputes: '/disputes',
  businesses: '/businesses',
  businessSetup: '/businesses/setup',
  professional: '/professional',
  parcels: '/parcels',
  p2p: '/p2p',
  marketplace: '/marketplace',
  myPublications: '/publications/mine',
  myListings: '/publications/mine',
  jobs: '/jobs',
  jobApplications: '/jobs/applications',
  events: '/events',
  messages: '/messages',
  notifications: '/notifications',
  support: '/support',
  admin: '/admin',
  featureMatrix: '/feature-matrix',
  superadmin: '/superadmin',
}

export const SIMPLE_LEGACY_REDIRECTS = [
  ['/home', ROUTES.dashboard],
  ['/accueil', ROUTES.dashboard],
  ['/actualites', ROUTES.news],
  ['/actualite', ROUTES.news],
  ['/transfer', ROUTES.transfers],
  ['/business', ROUTES.businesses],
  ['/business-dashboard', ROUTES.professional],
  ['/dashboard-entreprise', ROUTES.professional],
  ['/colis', ROUTES.parcels],
  ['/parcel', ROUTES.parcels],
  ['/p2p-detail', ROUTES.p2p],
  ['/conversations', ROUTES.messages],
  ['/message', ROUTES.messages],
  ['/community-management', ROUTES.jobApplications],
]

export const MARKETPLACE_LEGACY_PATHS = ['sales', 'market', 'annonces', 'vente', 'ventes']
export const MY_LISTINGS_LEGACY_PATHS = ['my-sales', 'my-listings', 'mes-annonces']
