import {
  OWNER_ID,
  PUBLISHER_NAME,
  PUBLISHER_PHONE,
  publishedAt,
  futureDate,
  eventStart,
  expiresInDays,
} from './catalogSeedUtils.mjs'

export { OWNER_ID, PUBLISHER_NAME, PUBLISHER_PHONE }

export const LISTINGS = [
  {
    id: 'ANN-MOX-01',
    title: 'Samsung Galaxy A54 5G — 128 Go, état impeccable',
    description:
      'Vends mon Galaxy A54 acheté en décembre 2025 chez M.Video. Écran Super AMOLED sans rayure, batterie tient facilement la journée. Coque + verre trempé inclus. Facture disponible. Je préfère remise en main propre à Moscou (métro Universitet).',
    price: 18500,
    currency: 'RUB',
    category: 'electronics',
    city: 'Moscou',
    country: 'RU',
    condition: 'like_new',
    images: [
      'https://images.unsplash.com/photo-1610945265064-753e6e5e8c2e?w=800&q=80',
      'https://images.unsplash.com/photo-1598327275664-199b4fd1ad8a?w=800&q=80',
    ],
    created_at: publishedAt(-9, 19, 42),
  },
  {
    id: 'ANN-MOX-02',
    title: 'Canapé d\'angle gris — 3 places, tissu déhoussable',
    description:
      'Canapé confortable, idéal pour salon ou studio. Couleur gris anthracite, peu servi (déménagement). Dimensions : 240 × 160 cm. À récupérer au 4e sans ascenseur — je peux aider à descendre. Disponible week-end prochain.',
    price: 22000,
    currency: 'RUB',
    category: 'home',
    city: 'Moscou',
    country: 'RU',
    condition: 'good',
    images: [
      'https://images.unsplash.com/photo-1555041469-a586c12ea9bc?w=800&q=80',
      'https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?w=800&q=80',
    ],
    created_at: publishedAt(-8, 11, 15),
  },
  {
    id: 'ANN-MOX-03',
    title: 'Vélo urbain Decathlon Elops 520 — taille L',
    description:
      'Vélo city avec panier avant, garde-boue et éclairage intégré. Entretien fait en juin (freins + chaîne). Quelques traces d\'usage normales. Parfait pour trajets quotidiens jusqu\'à 15 km. Casque offert si sérieux.',
    price: 12500,
    currency: 'RUB',
    type: 'vehicle',
    category: 'bicycle',
    city: 'Saint-Pétersbourg',
    country: 'RU',
    condition: 'good',
    images: [
      'https://images.unsplash.com/photo-1485965120188-e220f721d03e?w=800&q=80',
      'https://images.unsplash.com/photo-1571068316344-75bc76f77890?w=800&q=80',
    ],
    created_at: publishedAt(-7, 20, 8),
  },
  {
    id: 'ANN-MOX-04',
    title: 'MacBook Air M1 2020 — 8 Go / 256 Go SSD',
    description:
      'MacBook Air en excellent état, cycle batterie ~380. Utilisé surtout pour études et bureautique. Boîtier + chargeur d\'origine. macOS Sonoma à jour. Pas de chocs ni pixels morts. Échange possible contre iPad récent.',
    price: 52000,
    currency: 'RUB',
    category: 'electronics',
    city: 'Moscou',
    country: 'RU',
    condition: 'like_new',
    images: [
      'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&q=80',
      'https://images.unsplash.com/photo-1611186871348-b1ce696e52be?w=800&q=80',
    ],
    created_at: publishedAt(-6, 14, 33),
  },
  {
    id: 'ANN-MOX-05',
    title: 'Robot cuisine Moulinex Companion — quasi neuf',
    description:
      'Robot multifonction avec balance intégrée. Utilisé une dizaine de fois seulement. Accessoires complets (couteaux, spatule, livre de recettes). Parfait pour batch cooking le dimanche. Vends car je pars en stage à l\'étranger.',
    price: 15800,
    currency: 'RUB',
    category: 'home',
    city: 'Kazan',
    country: 'RU',
    condition: 'like_new',
    images: [
      'https://images.unsplash.com/photo-1570222094114-d054a817e56a?w=800&q=80',
    ],
    created_at: publishedAt(-5, 9, 50),
  },
  {
    id: 'ANN-MOX-06',
    title: 'Manteau d\'hiver The North Face — homme M',
    description:
      'Doudoune imperméable, chaude jusqu\'à -25 °C testée l\'hiver dernier. Taille M (175 cm / 72 kg). Couleur noir mat. Une petite accroche invisible sur la poche intérieure. Lavé en pressing avant mise en vente.',
    price: 8900,
    currency: 'RUB',
    category: 'fashion',
    city: 'Moscou',
    country: 'RU',
    condition: 'good',
    images: [
      'https://images.unsplash.com/photo-1539533018447-63fcce267608?w=800&q=80',
      'https://images.unsplash.com/photo-1544022613-e87ca75a784a?w=800&q=80',
    ],
    created_at: publishedAt(-4, 16, 22),
  },
  {
    id: 'ANN-MOX-07',
    title: 'PlayStation 5 Digital + 2 manettes + 4 jeux',
    description:
      'PS5 Digital Edition, achetée en 2024. Fonctionne parfaitement, ventilateur silencieux. Jeux inclus : FIFA 24, Spider-Man 2, It Takes Two, Gran Turismo 7 (comptes détachés). Câble HDMI neuf. Négociable si retrait rapide.',
    price: 38000,
    currency: 'RUB',
    category: 'electronics',
    city: 'Novossibirsk',
    country: 'RU',
    condition: 'good',
    images: [
      'https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=800&q=80',
      'https://images.unsplash.com/photo-1486401899868-0e435ed85128?w=800&q=80',
    ],
    created_at: publishedAt(-3, 21, 5),
  },
  {
    id: 'ANN-MOX-08',
    title: 'Bureau IKEA Bekant — 160×80 cm, réglable en hauteur',
    description:
      'Bureau assis-debout électrique, plateau blanc. Moteur OK, mémoire 2 positions. Idéal télétravail. Quelques marques légères sur le plateau (voir photo). Démonté et prêt à charger. Instructions IKEA fournies.',
    price: 14500,
    currency: 'RUB',
    category: 'home',
    city: 'Moscou',
    country: 'RU',
    condition: 'good',
    images: [
      'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=800&q=80',
      'https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?w=800&q=80',
    ],
    created_at: publishedAt(-2, 10, 40),
  },
  {
    id: 'ANN-MOX-09',
    title: 'Guitare acoustique Yamaha F310 — débutant / intermédiaire',
    description:
      'Yamaha F310, cordes neuves (D\'Addario). Son clair, manche confortable. Quelques micro-rayures sur le vernis — rien de gênant. Housse souple incluse. Je donne aussi mes partitions PDF de bases africaines et blues.',
    price: 7200,
    currency: 'RUB',
    category: 'sport',
    city: 'Moscou',
    country: 'RU',
    condition: 'good',
    images: [
      'https://images.unsplash.com/photo-1510915361894-db8b60106cb1?w=800&q=80',
      'https://images.unsplash.com/photo-1525201548942-d8732f6617a0?w=800&q=80',
    ],
    created_at: publishedAt(-1, 18, 12),
  },
  {
    id: 'ANN-MOX-10',
    title: 'Poussette Cybex Balios S — négociable, très propre',
    description:
      'Poussette 3-en-1 (landau + siège + coque adaptateur). Utilisée 8 mois, toujours entretenue. Roues gonflables, frein pied, capote XXL UV50+. Parfait état général — on upgrade pour jumeaux 😅. Retrait Moscou Sud.',
    price: 19500,
    currency: 'RUB',
    category: 'home',
    city: 'Moscou',
    country: 'RU',
    condition: 'like_new',
    images: [
      'https://images.unsplash.com/photo-1515488042361-ee00e3ddd4e7?w=800&q=80',
      'https://images.unsplash.com/photo-1584464491033-06628f3a6b7b?w=800&q=80',
    ],
    created_at: publishedAt(0, 8, 27),
  },
]

export const JOBS = [
  {
    id: 'JOB-MOX-01',
    title: 'Développeur React / Node.js — startup fintech diaspora',
    description:
      'On monte une équipe pour une app de transferts et marketplace ciblant la diaspora en Russie. Stack : React, Node, Supabase, TypeScript. Remote possible 2 j/sem. Anglais + français appréciés. Portfolio GitHub obligatoire.',
    sector: 'Technologie & informatique',
    contractType: 'full_time',
    experienceLevel: 'mid',
    language: 'fr_ru',
    salary: '215000',
    salaryPeriod: 'month',
    city: 'Moscou',
    remote: true,
    images: ['https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&q=80'],
    created_at: publishedAt(-8, 10, 0),
  },
  {
    id: 'JOB-MOX-02',
    title: 'Comptable senior — cabinet diaspora FR/RU',
    description:
      'Cabinet comptable spécialisé expatriés africains et francophones. Missions : déclarations, TVA, paie. 1C + Excel avancé. Russe courant + français natif. CDI après période d\'essai.',
    sector: 'Finance & comptabilité',
    contractType: 'full_time',
    experienceLevel: 'senior',
    language: 'fr_ru',
    salary: '140000',
    salaryPeriod: 'month',
    city: 'Moscou',
    remote: false,
    images: ['https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&q=80'],
    created_at: publishedAt(-7, 14, 30),
  },
  {
    id: 'JOB-MOX-03',
    title: 'Infirmier(ère) — clinique privée multilingue',
    description:
      'Clinique à Saint-Pétersbourg recherche infirmier pour service ambulatoire. Horaires en rotation. Diplôme reconnu + russe B2 minimum. Français ou anglais = plus. Formation interne fournie.',
    sector: 'Santé & bien-être',
    contractType: 'full_time',
    experienceLevel: 'junior',
    language: 'fr_ru',
    salary: '97500',
    salaryPeriod: 'month',
    city: 'Saint-Pétersbourg',
    remote: false,
    images: ['https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=800&q=80'],
    created_at: publishedAt(-6, 9, 15),
  },
  {
    id: 'JOB-MOX-04',
    title: 'Chef de projet logistique Afrique–Europe',
    description:
      'Coordination envois colis et partenariats transporteurs (BJ, TG, CM, GH → RU). Suivi douanes, relation clients diaspora. Déplacements occasionnels. Anglais + français exigés, russe B1+.',
    sector: 'Transport & logistique',
    contractType: 'full_time',
    experienceLevel: 'mid',
    language: 'fr_ru',
    salary: '175000',
    salaryPeriod: 'month',
    city: 'Moscou',
    remote: true,
    images: ['https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&q=80'],
    created_at: publishedAt(-5, 11, 45),
  },
  {
    id: 'JOB-MOX-05',
    title: 'Responsable marketing digital — marque mode africaine',
    description:
      'Lancement collection capsule en Russie. Missions : réseaux sociaux, influenceurs diaspora, campagnes VK/Telegram. Créatif + data. CDI, équipe jeune et dynamique à Moscou.',
    sector: 'Arts & communication',
    contractType: 'full_time',
    experienceLevel: 'mid',
    language: 'fr',
    salary: '120000',
    salaryPeriod: 'month',
    city: 'Moscou',
    remote: true,
    images: ['https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80'],
    created_at: publishedAt(-4, 16, 0),
  },
  {
    id: 'JOB-MOX-06',
    title: 'Job d\'été — serveur(se) restaurant fusion afro-européen',
    description:
      'Restaurant à Arbat ouvre terrasse d\'été. Shift soir + week-end. Formation 3 jours payée. Bon pour étudiants avec russe conversationnel. Pourboires en plus du fixe horaire.',
    sector: 'Restauration & hôtellerie',
    contractType: 'contract',
    experienceLevel: 'none',
    language: 'fr_ru',
    salary: '350',
    salaryPeriod: 'hour',
    city: 'Moscou',
    remote: false,
    images: ['https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&q=80'],
    created_at: publishedAt(-3, 12, 20),
  },
  {
    id: 'JOB-MOX-07',
    title: 'Baby-sitting week-end — famille bilingue FR/RU',
    description:
      'Garde de 2 enfants (5 et 8 ans) samedi 10h–18h près du métro Sokol. Activités calmes, sorties parc. Français natif souhaité. Contrat ponctuel, possibilité long terme si affinité.',
    sector: 'Services à la personne',
    contractType: 'part_time',
    experienceLevel: 'junior',
    language: 'fr_ru',
    salary: '500',
    salaryPeriod: 'hour',
    city: 'Moscou',
    remote: false,
    images: ['https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=800&q=80'],
    created_at: publishedAt(-2, 19, 10),
  },
  {
    id: 'JOB-MOX-08',
    title: 'Stage rémunéré — community manager MOXT (3 mois)',
    description:
      'Aide modération feed, réponses messages, petits visuels Canva. 20 h/semaine flexible autour des cours. Idéal étudiant info-com ou marketing. Possibilité embauche après stage.',
    sector: 'Technologie & informatique',
    contractType: 'internship',
    experienceLevel: 'none',
    language: 'fr_ru',
    salary: '25000',
    salaryPeriod: 'month',
    city: 'Moscou (remote)',
    remote: true,
    images: ['https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=800&q=80'],
    created_at: publishedAt(-1, 15, 55),
  },
  {
    id: 'JOB-MOX-09',
    title: 'Cours particuliers maths — lycée / première année sup',
    description:
      'Professeur agrégé (diaspora) cherche aide pour groupes de 3–4 élèves le mercredi soir. Prépa bac russe + entrée université. 90 min/seance. Lieu : bibliothèque ou visio.',
    sector: 'Enseignement & formation',
    contractType: 'part_time',
    experienceLevel: 'mid',
    language: 'fr_ru',
    salary: '1500',
    salaryPeriod: 'project',
    city: 'Moscou',
    remote: true,
    images: ['https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800&q=80'],
    created_at: publishedAt(-1, 8, 30),
  },
  {
    id: 'JOB-MOX-10',
    title: 'Extra événementiel — accueil soirée diaspora (17 août)',
    description:
      'Soirée networking 200 personnes à Moscou. Accueil, vestiaire, orientation tables. Tenue smart casual fournie (polo). Paiement le soir même. Une soirée, mais on recrute aussi pour septembre.',
    sector: 'Autre',
    contractType: 'contract',
    experienceLevel: 'none',
    language: 'fr_ru',
    salary: '4000',
    salaryPeriod: 'project',
    city: 'Moscou',
    remote: false,
    images: ['https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&q=80'],
    created_at: publishedAt(0, 7, 45),
  },
]

export const EVENTS = [
  {
    id: 'EVT-MOX-01',
    title: 'Soirée networking diaspora africaine à Moscou',
    description:
      'Rencontre informelle autour d\'un buffet et de musique afrobeat. Entrepreneurs, étudiants, expatriés — venez avec votre sourire et vos cartes de visite (ou QR MOXT 😄). Entrée libre sur inscription.',
    category: 'networking',
    city: 'Moscou',
    country: 'RU',
    venue: 'Espace coworking Arbat, 12 Malaya Nikitskaya',
    starts_at: eventStart(12, 19, 0),
    ends_at: eventStart(12, 23, 0),
    max_attendees: 120,
    images: ['https://images.unsplash.com/photo-1511578314322-379afb476865?w=800&q=80'],
    created_at: publishedAt(-9, 20, 0),
  },
  {
    id: 'EVT-MOX-02',
    title: 'Concert live — Afro Fusion Night',
    description:
      'Line-up : DJ Koffi (Abidjan), live band Moscou, surprise guest. Bar et snacks sur place. Tenue : chic décontracté. Billets limités — réservez tôt.',
    category: 'culture',
    format: 'in_person',
    city: 'Moscou',
    country: 'RU',
    venue: 'Club Gipsy, Bolotnaya Naberezhnaya 16',
    starts_at: eventStart(18, 21, 0),
    ends_at: eventStart(19, 2, 0),
    max_attendees: 300,
    images: ['https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=800&q=80'],
    created_at: publishedAt(-8, 13, 25),
  },
  {
    id: 'EVT-MOX-03',
    title: 'Atelier cuisine — thiéboudienne maison',
    description:
      'Chef sénégalaise vous guide pas à pas : riz, poisson, légumes, épices. Dégustation collective à la fin. Aprons fournis, apportez juste votre bonne humeur (et un récipient si vous voulez des restes 😉).',
    category: 'community',
    format: 'in_person',
    city: 'Moscou',
    country: 'RU',
    venue: 'Cuisine collective « Taste of Africa », m. Prospekt Mira',
    starts_at: eventStart(8, 11, 0),
    ends_at: eventStart(8, 14, 30),
    max_attendees: 16,
    images: ['https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=800&q=80'],
    created_at: publishedAt(-7, 10, 10),
  },
  {
    id: 'EVT-MOX-04',
    title: 'Forum emploi — opportunités diaspora 2026',
    description:
      'Tables rondes RH, CV check express, stands entreprises partenaires. Sessions en français et russe. Gratuit pour inscrits MOXT. Bring printed CV if you can.',
    category: 'business',
    format: 'in_person',
    city: 'Saint-Pétersbourg',
    country: 'RU',
    venue: 'Université HSE, room 301',
    starts_at: eventStart(22, 10, 0),
    ends_at: eventStart(22, 17, 0),
    max_attendees: 200,
    images: ['https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&q=80'],
    created_at: publishedAt(-6, 9, 0),
  },
  {
    id: 'EVT-MOX-05',
    title: 'Match de foot amical — Afrique vs Reste du monde',
    description:
      '7 contre 7, niveau loisir (on rigole plus qu\'on ne se bat 😅). Chaussures indoor, maillets fournis. Après-match : thé et discussions sur la CAN 2025.',
    category: 'community',
    format: 'in_person',
    city: 'Moscou',
    country: 'RU',
    venue: 'Complexe sportif Luzhniki, terrain synthétique 3',
    starts_at: eventStart(5, 18, 30),
    ends_at: eventStart(5, 21, 0),
    max_attendees: 28,
    images: ['https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=800&q=80'],
    created_at: publishedAt(-5, 17, 40),
  },
  {
    id: 'EVT-MOX-06',
    title: 'Projection + débat — « Afrique et tech »',
    description:
      'Documentaire 52 min suivi d\'un débat avec deux fondateurs de startups. Popcorn et boissons inclus. Places assises numérotées.',
    category: 'culture',
    format: 'in_person',
    city: 'Moscou',
    country: 'RU',
    venue: 'Cinéma Pioner, Kutuzovsky 47',
    starts_at: eventStart(15, 19, 30),
    ends_at: eventStart(15, 22, 0),
    max_attendees: 80,
    images: ['https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=800&q=80'],
    created_at: publishedAt(-4, 14, 15),
  },
  {
    id: 'EVT-MOX-07',
    title: 'Marché artisanal — créateurs afro-diaspora',
    description:
      'Bijoux, mode, cosmétiques naturels, art. 25 exposants. Espace kids avec contes. Entrée 200 ₽ reversée à une asso locale.',
    category: 'business',
    format: 'in_person',
    city: 'Kazan',
    country: 'RU',
    venue: 'Parc central, tente B12',
    starts_at: eventStart(10, 10, 0),
    ends_at: eventStart(11, 20, 0),
    max_attendees: 500,
    images: ['https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800&q=80'],
    created_at: publishedAt(-3, 11, 0),
  },
  {
    id: 'EVT-MOX-08',
    title: 'Webinaire — créer son statut en Russie (2026)',
    description:
      'Avocat et expert comptable répondent aux questions : patent, LLC, impôts, banque. Q&A live en fin de session. Lien Zoom envoyé 24 h avant.',
    category: 'training',
    format: 'online',
    city: 'En ligne',
    country: 'RU',
    venue: 'Zoom (lien après inscription)',
    starts_at: eventStart(6, 18, 0),
    ends_at: eventStart(6, 20, 0),
    max_attendees: 150,
    images: ['https://images.unsplash.com/photo-1591115765373-5207764f72e7?w=800&q=80'],
    created_at: publishedAt(-2, 16, 30),
  },
  {
    id: 'EVT-MOX-09',
    title: 'Picnic dimanche — parc Kolomenskoye',
    description:
      'On partage plats maison, frisbee, musique enceinte (volume raisonnable 🙏). Apportez un plat ou une boisson à partager. Rencontre au pont près de l\'église à 13h pile.',
    category: 'community',
    format: 'in_person',
    city: 'Moscou',
    country: 'RU',
    venue: 'Parc Kolomenskoye, entrée principale',
    starts_at: eventStart(3, 13, 0),
    ends_at: eventStart(3, 18, 0),
    max_attendees: 40,
    images: ['https://images.unsplash.com/photo-1528607929212-2636ec44253e?w=800&q=80'],
    created_at: publishedAt(-1, 21, 0),
  },
  {
    id: 'EVT-MOX-10',
    title: 'Hackathon 48 h — solutions pour la diaspora',
    description:
      'Thèmes : colis, jobs, santé, éducation. Équipes 3–5 personnes. Mentors tech + juristes. Repas et café sur place. Prix : 150 000 ₽ + accompagnement incubateur.',
    category: 'training',
    format: 'in_person',
    city: 'Moscou',
    country: 'RU',
    venue: 'Digital October, Bersenevskaya 14',
    starts_at: eventStart(25, 9, 0),
    ends_at: eventStart(27, 18, 0),
    max_attendees: 60,
    images: ['https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=800&q=80'],
    created_at: publishedAt(0, 6, 15),
  },
]

const AIRPORTS = {
  BJ: { city: 'Cotonou', code: 'COO' },
  TG: { city: 'Lomé', code: 'LFW' },
  CM: { city: 'Douala', code: 'DLA' },
  GH: { city: 'Accra', code: 'ACC' },
  RU: { city: 'Moscou', code: 'SVO' },
}

function parcel(id, from, to, summary, details, weightKg, pricePerKg, daysUntilDeparture, dayOffset, hour) {
  const departure = futureDate(daysUntilDeparture)
  const created = publishedAt(dayOffset, hour)
  const deposit = futureDate(Math.max(3, daysUntilDeparture - 4))
  const distribution = futureDate(daysUntilDeparture + 6)
  const origin = AIRPORTS[from] || AIRPORTS.BJ
  const destination = AIRPORTS[to] || AIRPORTS.RU

  return {
    id,
    from_country: from,
    to_country: to,
    origin: origin.city,
    destination: destination.city,
    origin_airport_code: origin.code,
    destination_airport_code: destination.code,
    departure_date: departure,
    deposit_deadline: deposit,
    distribution_date: distribution,
    capacity_kg: weightKg,
    remaining_kg: weightKg,
    price_per_kg: pricePerKg,
    currency: 'RUB',
    conditions: `${summary}. ${details}`,
    contact: PUBLISHER_PHONE,
    accepted_types: ['documents', 'clothing', 'electronics', 'cosmetics'],
    rejected_types: '',
    summary,
    details,
    weightKg,
    pricePerKg,
    daysUntilDeparture,
    dayOffset,
    hour,
    created_at: created,
  }
}

export const PARCELS = [
  // Bénin → Russie (5)
  parcel('COL-MOX-BJ01', 'BJ', 'RU', 'Vêtements wax et pagnes', 'Deux sacs textile bien emballés. Livraison main propre Moscou sud. Pas de produits alimentaires.', 8, 560, 14, -9, 10),
  parcel('COL-MOX-BJ02', 'BJ', 'RU', 'Parfums et cosmétiques artisanaux', 'Cartons scellés, factures disponibles. Fragile — éviter chocs. Contact WhatsApp avant envoi.', 5, 640, 18, -8, 15),
  parcel('COL-MOX-BJ03', 'BJ', 'RU', 'Documents + petits cadeaux famille', 'Enveloppe renforcée + boîte chaussures. Budget serré — prix juste apprécié.', 3, 600, 10, -7, 9),
  parcel('COL-MOX-BJ04', 'BJ', 'RU', 'Pièces détachées moto', 'Moteur secondaire démonté, photos sur demande. Transporteur habitué pièces lourdes.', 22, 445, 21, -6, 14),
  parcel('COL-MOX-BJ05', 'BJ', 'RU', 'Épices et condiments secs', 'Sachets sous vide, étiquetés. Déclaration douane OK.', 6, 470, 16, -5, 11),
  // Togo (5)
  parcel('COL-MOX-TG01', 'TG', 'RU', 'Statuettes art Ewe', 'Objets déco fragiles, double cartonnage. Assurance recommandée.', 4, 875, 12, -9, 16),
  parcel('COL-MOX-TG02', 'TG', 'RU', 'Laptop ThinkPad T480 + chargeur', 'Batterie OK. Valeur déclarée 400 €. Voyageur de confiance avec références MOXT.', 2.5, 880, 15, -8, 8),
  parcel('COL-MOX-TG03', 'TG', 'RU', 'Médicaments sur ordonnance', 'Boîtes scellées, ordonnances scannées disponibles. Conformité douanière stricte.', 1.5, 1000, 20, -7, 13),
  parcel('COL-MOX-TG04', 'TG', 'RU', 'Sacs à main artisanaux (lot 12)', 'Bonne marge pour revendeuse Moscou si vous connaissez le milieu.', 9, 467, 19, -6, 17),
  parcel('COL-MOX-TG05', 'TG', 'RU', 'Livres scolaires francophones', 'CM1 à terminale, ~15 kg. École diaspora Moscou — budget associatif limité.', 15, 367, 23, -5, 10),
  // Cameroun (5)
  parcel('COL-MOX-CM01', 'CM', 'RU', 'Tenues de cérémonie (mariage)', 'Costumes et robes. Housse garment incluse. Départ impératif avant le 5 août.', 7, 686, 11, -9, 12),
  parcel('COL-MOX-CM02', 'CM', 'RU', 'Cacao fèves et poudre (export légal)', 'Producteur certifié, documents phytosanitaires OK.', 10, 620, 17, -8, 18),
  parcel('COL-MOX-CM03', 'CM', 'RU', 'Console Mega Drive + 8 jeux', 'Nostalgie garantie 😄. Emballage bulle soigné.', 3, 800, 14, -7, 11),
  parcel('COL-MOX-CM04', 'CM', 'RU', 'Pièces auto (filtres, plaquettes)', 'Carton 12 kg, marque Bosch/Valeo. Garage Moscou attend livraison mi-août.', 12, 425, 20, -6, 9),
  parcel('COL-MOX-CM05', 'CM', 'RU', 'Produits capillaires naturels', 'Beurre karité, huiles, masques — boutique diaspora. Clientèle fidèle.', 8, 450, 16, -5, 15),
  // Ghana (5)
  parcel('COL-MOX-GH01', 'GH', 'RU', 'Tissus kente Ashanti', 'Rouleaux protégés plastique. Pas de pliage serré. Photo échantillon dispo.', 6, 650, 13, -9, 14),
  parcel('COL-MOX-GH02', 'GH', 'RU', 'Accessoires MacBook + hub USB-C', 'Petit colis high-tech, valeur ~300 $. Emballage d\'origine Apple.', 1.2, 1330, 10, -8, 10),
  parcel('COL-MOX-GH03', 'GH', 'RU', 'Shea butter cosmétique (6 cartons)', 'Export Ghana approuvé, étiquettes INCI. Prix négociable volume.', 11, 400, 18, -7, 16),
  parcel('COL-MOX-GH04', 'GH', 'RU', 'Djembé compact 12"', 'Peau chèvre, housse incluse. Fragile — voyageur expérimenté only.', 5, 820, 22, -6, 12),
  parcel('COL-MOX-GH05', 'GH', 'RU', 'Mangues séchées et snacks', 'Sous vide, cadeaux famille — consommation perso, pas revente.', 4, 675, 15, -5, 8),
]
