/** Classes Tailwind copiées depuis moxt-react NewTransferPage + TransferDetail */
export const twTransfer = {
  page: 'gap-7 bg-app-bg dark:bg-[#0c0c0e]',
  scroll: 'gap-5 px-4 pb-32 pt-2',

  stepperWrap: 'rounded-2xl bg-app-surface px-6 py-5 shadow-sm ',

  card: 'gap-5 rounded-2xl bg-app-surface p-5 shadow-sm ',
  sectionTitle: 'flex-row items-center gap-3 border-b border-app-border pb-4',
  sectionIcon: 'h-9 w-9 items-center justify-center rounded-xl bg-brand-100 dark:bg-brand-950/45',
  sectionLabel: 'font-black text-app-text',

  directionCard: 'rounded-2xl border-2 p-5',
  directionCardActive: 'border-brand-700 bg-brand-50 shadow-md dark:border-brand-400 dark:bg-brand-950/40',
  directionCardIdle: 'border-app-border',
  directionFlags: 'text-lg font-black text-app-text',
  directionSub: 'mt-1 text-xs font-bold',
  selectedPill: 'mt-3 self-start rounded-full px-2.5 py-1',
  selectedPillText: 'text-[10px] font-bold text-white',

  fieldLabel: 'mb-1.5 text-[10px] font-black uppercase tracking-wider text-app-text-faint',
  amountInput: 'min-h-14 rounded-2xl bg-app-surface-muted px-4 text-2xl font-black text-app-text',
  fieldInput: 'min-h-14 rounded-2xl bg-app-surface-muted px-4 text-base font-bold text-app-text',
  infoBox: 'flex-row items-start gap-3 rounded-2xl bg-brand-100 p-4 dark:bg-brand-950/30',
  infoText: 'flex-1 text-sm text-app-text-muted',

  partnerHeader: 'flex-row items-center justify-between gap-3 border-b border-app-border pb-4',
  partnerCard: 'w-[9.25rem] shrink-0 flex-col items-center gap-2 rounded-2xl border-2 p-4',
  partnerCardActive: 'border-emerald-500 bg-emerald-50 shadow-md dark:border-emerald-400 dark:bg-emerald-950/40',
  partnerCardIdle: 'border-app-border',
  partnerAvatar: 'h-12 w-12 items-center justify-center rounded-2xl',
  partnerName: 'text-center text-xs font-black leading-tight text-app-text',
  partnerRating: 'text-[10px] font-bold text-amber-600',
  partnerTag: 'rounded-full px-2 py-0.5 text-[10px] font-bold',
  partnerSelected: 'text-[10px] font-bold text-emerald-700 dark:text-emerald-300',

  simGradient: 'p-5',
  simEyebrow: 'text-xs font-bold uppercase tracking-widest text-white/80',
  simPayLabel: 'text-xs font-bold text-white/70',
  simPayValue: 'text-2xl font-black text-white',
  simRatePill: 'rounded-full bg-white/20 px-3 py-1',
  simRateText: 'text-[10px] font-bold text-white',
  simGrid: 'flex-row border-b border-app-border',
  simGridCell: 'flex-1 items-center gap-0.5 px-4 py-3',
  simGridLabel: 'text-[10px] font-bold uppercase tracking-wide text-app-text-faint',
  simGridValue: 'text-sm font-black text-app-text',
  simGridValueHighlight: 'text-sm font-black text-red-500',
  simFooter: 'gap-3 p-5',
  simFooterNote: 'text-[10px] leading-5 text-app-text-faint',

  partyHeaderSender: 'bg-brand-100 dark:bg-brand-950/45',
  partyHeaderRecipient: 'bg-cyan-100 dark:bg-cyan-950/40',
  methodChip: 'rounded-full px-3 py-2',
  methodChipActive: 'bg-brand-700 dark:bg-brand-400',
  methodChipIdle: 'bg-app-surface-muted',
  methodChipTextActive: 'text-xs font-bold text-white dark:text-slate-950',
  methodChipTextIdle: 'text-xs font-bold text-app-text',
  helperText: 'text-xs text-app-text-muted',

  confirmGradient: 'flex-row items-center justify-between gap-4 rounded-2xl p-5',
  confirmRow: 'flex-row justify-between gap-4 rounded-xl bg-app-surface-muted px-4 py-3',
  confirmRowLabel: 'text-sm text-app-text-muted',
  confirmRowValue: 'text-right text-sm font-bold text-app-text',
  termsBox: 'flex-row items-start gap-3 rounded-2xl border-2 border-app-border p-4',
  termsText: 'flex-1 text-sm leading-relaxed text-app-text',
  checkbox: 'mt-0.5 h-4 w-4 items-center justify-center rounded border-2',
  submitBtn: 'min-h-11 w-full flex-row items-center justify-center gap-2 rounded-[0.75rem] bg-brand-700 px-5 dark:bg-brand-400',
  submitBtnText: 'text-sm font-black text-white dark:text-slate-950',

  navRow: 'flex-row justify-between gap-3',
  navBack: 'min-h-11 flex-1 flex-row items-center justify-center gap-2 rounded-[0.75rem] bg-app-surface-muted',
  navBackText: 'text-sm font-bold text-app-text',
  navNext: 'min-h-11 flex-1 flex-row items-center justify-center gap-2 rounded-[0.75rem] bg-brand-700 dark:bg-brand-400',
  navNextText: 'text-sm font-black text-white dark:text-slate-950',

  /* Detail */
  detailHero: 'overflow-hidden rounded-2xl',
  detailHeroBadge: 'absolute right-3 top-0 rounded-full px-2.5 py-1',
  detailHeroBadgeText: 'text-[9px] font-black uppercase tracking-wide',
  detailHeroLabel: 'text-[10px] font-bold uppercase tracking-wider text-white/65',
  detailHeroValue: 'mt-1 text-2xl font-black text-white',
  detailHeroPartner: 'mt-5 flex-row items-center gap-2 border-t border-white/15 pt-4',
  detailHeroPartnerText: 'text-xs text-white/75',
  detailVerified: 'rounded-full border border-white/25 bg-white/10 px-2 py-0.5',
  detailVerifiedText: 'text-[9px] font-black text-white',

  detailCard: 'rounded-2xl bg-app-surface p-5 shadow-sm ',
  detailCardTitle: 'text-lg font-black text-app-text',
  detailMetricGrid: 'flex-row flex-wrap gap-3',
  detailMetric: 'w-[48%] rounded-2xl border border-app-border bg-app-surface p-4 shadow-sm',
  detailMetricLabel: 'text-xs text-app-text-muted',
  detailMetricValue: 'mt-1 text-base font-black text-app-text',

  progressRow: 'mt-4 flex-row justify-between',
  progressCircle: 'h-8 w-8 items-center justify-center rounded-full border-2',
  progressLabel: 'mt-1.5 text-[9px] font-semibold text-center',

  warningCard: 'rounded-2xl border border-amber-200 bg-amber-50 p-5 dark:border-amber-900/50 dark:bg-amber-950/30',
  warningTitle: 'text-sm font-black text-amber-900 dark:text-amber-200',
  warningText: 'mt-2 text-xs leading-relaxed text-amber-800 dark:text-amber-300',

  nextEyebrow: 'text-[10px] font-black uppercase tracking-widest text-brand-700 dark:text-brand-400',
  nextTitle: 'text-xl font-black text-app-text',
  nextDesc: 'mt-2 text-sm leading-relaxed text-app-text-muted',
  statusPill: 'rounded-full px-2.5 py-1',
  statusPillText: 'text-[9px] font-black uppercase',

  financeRow: 'flex-row justify-between gap-4 border-b border-app-border py-4',
  financeLabel: 'flex-1 text-sm text-app-text-muted',
  financeValue: 'flex-1 text-right text-sm font-bold text-app-text',
  actionChip: 'rounded-full bg-app-surface-muted px-3.5 py-2',
  actionChipText: 'text-xs font-bold text-app-text-secondary',

  participantCard: 'flex-1 items-center rounded-2xl bg-app-surface-muted p-4',
  participantBadge: 'mb-2 h-10 w-10 items-center justify-center rounded-full bg-brand-700 dark:bg-brand-400',
  participantBadgeText: 'text-sm font-black text-white dark:text-slate-950',
  participantRole: 'text-[9px] font-black uppercase tracking-wider text-brand-700 dark:text-brand-400',
  participantName: 'mt-1 text-center text-sm font-black text-app-text',
  participantMeta: 'text-center text-xs text-app-text-muted',

  uploadZone: 'items-center rounded-2xl border border-dashed border-app-border bg-app-surface-muted p-6',
  uploadTitle: 'text-sm font-black text-app-text',
  uploadHint: 'mt-1 text-xs text-app-text-muted',

  declareBtn: 'min-h-11 flex-row items-center justify-center gap-2 rounded-[0.75rem] bg-brand-700/80 px-5 dark:bg-brand-400/90',
  cancelBtn: 'min-h-11 flex-row items-center justify-center rounded-[0.75rem] bg-red-50 dark:bg-red-950/30',
  cancelBtnText: 'text-sm font-bold text-red-600 dark:text-red-400',
  outlineBtn: 'min-h-11 flex-row items-center justify-center rounded-[0.75rem] bg-app-surface-muted',
  outlineBtnText: 'text-sm font-bold text-app-text',

  factBlock: 'mb-3 rounded-xl bg-app-surface-muted p-4',
  factLabel: 'text-[10px] font-black uppercase tracking-wider text-app-text-faint',
  factValue: 'mt-1 text-base font-black text-app-text',
} as const;
