# -*- coding: utf-8 -*-
"""Generate Neutral LatAm Spanish (tú) for rest4 batch from pt/fr/en."""
from __future__ import annotations

import json
import re
from pathlib import Path

SOURCE = Path(r"C:\Users\felic\Videos\Moxt\scripts\.es-batches\rest4.json")
DESTINATION = Path(r"C:\Users\felic\Videos\Moxt\scripts\.es-out\rest4.json")

# Exact overrides keyed by source string (pt preferred). Keep MOXT/P2P and {placeholders}.
OVERRIDES: dict[str, str] = {
    "Benim para Rússia": "Benín a Rusia",
    "Rússia para Benim": "Rusia a Benín",
    "África → Rússia": "África → Rusia",
    "Rússia → África": "Rusia → África",
    "Pagamento pendente": "Pago pendiente",
    "Pagamento declarado": "Pago declarado",
    "Pagamento recebido": "Pago recibido",
    "Em processamento": "En procesamiento",
    "Transferência efetuada": "Transferencia realizada",
    "Concluído": "Completado",
    "Cancelado": "Cancelado",
    "Expirado": "Vencido",
    "Criado": "Creado",
    "Declarado": "Declarado",
    "Recebido": "Recibido",
    "Pago": "Pagado",
    "Transferência criada, pagamento pendente": "Transferencia creada, pago pendiente",
    "Pagamento declarado pelo cliente": "Pago declarado por el cliente",
    "Pagamento recebido pelo parceiro": "Pago recibido por el socio",
    "Transferência antiga em processamento": "Transferencia antigua en procesamiento",
    "Transferência efetuada pela empresa": "Transferencia realizada por la empresa",
    "Pagamento validado, transferência concluída": "Pago validado, transferencia completada",
    "Transferência cancelada": "Transferencia cancelada",
    "Prazo de pagamento expirado": "Plazo de pago vencido",
    "Ação do cliente necessária": "Acción del cliente requerida",
    "Adicione um comprovativo e declare o pagamento. A empresa será notificada automaticamente.": "Agrega un comprobante y declara el pago. La empresa será notificada automáticamente.",
    "Ação da empresa necessária": "Acción de la empresa requerida",
    "O parceiro deve confirmar a receção do pagamento no painel.": "El socio debe confirmar la recepción del pago desde su panel.",
    "Transferência em preparação": "Transferencia en preparación",
    "A empresa deve efetuar a transferência e pode adicionar o comprovativo do envio.": "La empresa debe realizar la transferencia y puede agregar el comprobante del envío.",
    "Validação final pendente": "Validación final pendiente",
    "A empresa deve validar o fim da transferência. O recibo será depois guardado.": "La empresa debe confirmar el fin de la transferencia. Luego se guardará el recibo.",
    "Operação concluída": "Operación completada",
    "O recibo está disponível e a transferência já não pode ser cancelada.": "El recibo está disponible y la transferencia ya no se puede cancelar.",
    "Operação cancelada": "Operación cancelada",
    "Não é possível qualquer outra ação nesta transferência.": "No es posible ninguna otra acción en esta transferencia.",
    "Prazo ultrapassado": "Plazo superado",
    "O pagamento não foi declarado no prazo previsto.": "El pago no se declaró dentro del plazo previsto.",
    "Montante": "Monto",
    "Remetente": "Remitente",
    "Destinatário": "Destinatario",
    "Confirmar": "Confirmar",
    "Histórico": "Historial",
    "Transferências": "Transferencias",
    "Estime, crie e acompanhe as suas transferências entre o Benim e a Rússia.": "Estima, crea y sigue tus transferencias entre Benín y Rusia.",
    "Calculadora": "Calculadora",
    "Nova transferência": "Nueva transferencia",
    "{count} operação(ões)": "{count} operación(es)",
    "Referência, destinatário ou operação...": "Referencia, destinatario u operación...",
    "Estado": "Estado",
    "Todos os estados": "Todos los estados",
    "Enviado": "Enviado",
    "Taxas": "Comisiones",
    "Nenhuma transferência": "Ninguna transferencia",
    "Nenhum resultado corresponde à pesquisa.": "Ningún resultado coincide con tu búsqueda.",
    "Crie a sua primeira operação.": "Crea tu primera operación.",
    "Calculadora de transferência": "Calculadora de transferencia",
    "Estimativa à taxa de referência disponível, antes da confirmação da empresa.": "Estimación al tipo de cambio de referencia disponible, antes de la confirmación de la empresa.",
    "A atualizar…": "Actualizando…",
    "Direção": "Dirección",
    "XOF para RUB": "XOF a RUB",
    "RUB para XOF": "RUB a XOF",
    "Montante em {currency}": "Monto en {currency}",
    "Inverter o sentido da transferência": "Invertir el sentido de la transferencia",
    "O destinatário recebe": "El destinatario recibe",
    "Taxas {percent}%": "Comisiones {percent}%",
    "Total a pagar": "Total a pagar",
    "Corrija o montante para obter uma estimativa.": "Corrige el monto para obtener una estimación.",
    "data indisponível": "fecha no disponible",
    "1 {from} = {rate} {to}. Referência de {date}, com margem da plataforma de {margin}%.": "1 {from} = {rate} {to}. Referencia del {date}, con un margen de la plataforma del {margin}%.",
    "Transferência rápida": "Transferencia rápida",
    "Estime o seu envio": "Estima tu envío",
    "Envia": "Envías",
    "Estimativa recebida": "Estimación recibida",
    "Abrir calculadora": "Abrir calculadora",
    "Comprovativos": "Comprobantes",
    "Provas guardadas para esta transferência — sempre descarregáveis.": "Comprobantes guardados para esta transferencia — siempre descargables.",
    "Comprovativo de pagamento (cliente)": "Comprobante de pago (cliente)",
    "Pagamento do cliente": "Pago del cliente",
    "Comprovativo de transferência (empresa)": "Comprobante de transferencia (empresa)",
    "Transferência da empresa": "Transferencia de la empresa",
    "Comprovativo de receção": "Comprobante de recepción",
    "Receção": "Recepción",
    "Adicionado em {date}": "Agregado el {date}",
    "Descarregar": "Descargar",
    "Download impossível": "Descarga fallida",
    "Não foi possível obter o ficheiro. Tente novamente dentro de momentos.": "No se pudo obtener el archivo. Inténtalo de nuevo en un momento.",
    "MOXT - RECIBO DE TRANSFERÊNCIA": "MOXT - RECIBO DE TRANSFERENCIA",
    "Referência: {id}": "Referencia: {id}",
    "Estado: {status}": "Estado: {status}",
    "Direção: {direction}": "Dirección: {direction}",
    "Empresa: {name}": "Empresa: {name}",
    "Não indicado": "No indicado",
    "Remetente: {name}": "Remitente: {name}",
    "Destinatário: {name}": "Destinatario: {name}",
    "Montante enviado: {amount}": "Monto enviado: {amount}",
    "Taxas ({percent}%): {amount}": "Comisiones ({percent}%): {amount}",
    "Total pago: {amount}": "Total pagado: {amount}",
    "Montante recebido: {amount}": "Monto recibido: {amount}",
    "Criado em: {date}": "Creado el: {date}",
    "PROCESSAMENTO": "PROCESAMIENTO",
    "Documento gerado localmente pelo MOXT.": "Documento generado localmente por MOXT.",
    "Recibo {id}": "Recibo {id}",
    "Utilize \"Guardar como PDF\" na janela de impressão.": "Usa \"Guardar como PDF\" en el diálogo de impresión.",
    "Recibo MOXT {id}": "Recibo MOXT {id}",
    "Recibo de transferência {id}": "Recibo de transferencia {id}",
    "Dados de receção indisponíveis": "Datos de recepción no disponibles",
    "Esta empresa ainda não configurou a conta ativa para {direction}.": "Esta empresa aún no ha configurado la cuenta activa para {direction}.",
    "este sentido de transferência": "este sentido de transferencia",
    "Conta de receção ativa": "Cuenta de recepción activa",
    "Dados da empresa": "Datos de la empresa",
    "Ativo": "Activa",
    "Beneficiário": "Beneficiario",
    "Método": "Método",
    "Número ou conta": "Número o cuenta",
    "Banco": "Banco",
    "Copiar dados": "Copiar datos",
    "Numerário": "Efectivo",
    "Mobile money": "Mobile money",
    "Transferência bancária": "Transferencia bancaria",
    "Outro": "Otro",
    "Confirmar receção": "Confirmar recepción",
    "Montante recebido": "Monto recibido",
    "Ex. 125000": "Ej. 125000",
    "Método de receção": "Método de recepción",
    "Comprovativo de receção (opcional)": "Comprobante de recepción (opcional)",
    "A guardar…": "Guardando…",
    "Ação impossível": "Acción no disponible",
    "A empresa deve primeiro confirmar a transferência com comprovativo antes de declarar a receção.": "La empresa debe primero confirmar la transferencia con comprobante antes de que declares la recepción.",
    "Não foi possível enviar o comprovativo.": "No se pudo subir el comprobante.",
    "Copiado": "Copiado",
    "{label} copiado para a área de transferência.": "{label} copiado al portapapeles.",
    "Receção não encontrada": "Recepción no encontrada",
    "Transferência": "Transferencia",
    "Esta transferência não existe ou já não está acessível.": "Esta transferencia no existe o ya no está accesible.",
    "Voltar às transferências": "Volver a transferencias",
    "Receção registada": "Recepción registrada",
    "A sua declaração foi enviada. O cambista poderá validar a receção.": "Tu declaración fue enviada. El cambista podrá validar la recepción.",
    "Ver transferência": "Ver transferencia",
    "As minhas transferências": "Mis transferencias",
    "Declarar receção": "Declarar recepción",
    "Transferência {id}": "Transferencia {id}",
    "Resumo": "Resumen",
    "Montante recebido esperado": "Monto recibido esperado",
    "Cambista": "Cambista",
    "Conta de receção": "Cuenta de recepción",
    "Titular": "Titular",
    "Telefone": "Teléfono",
    "Dados": "Datos",
    "Saldo da carteira": "Saldo de la billetera",
    "Saldo atual: {balance} — a confirmação de receção ainda não ajusta automaticamente este saldo.": "Saldo actual: {balance} — confirmar la recepción aún no ajusta automáticamente este saldo.",
    "Percurso da transferência": "Recorrido de la transferencia",
    "{completed}/{total} etapas validadas": "{completed}/{total} pasos completados",
    "Apenas reclamação": "Solo reclamo",
    "Todas as etapas estão concluídas. Em caso de problema, abra uma reclamação.": "Todos los pasos están completos. Si hay un problema, abre un reclamo.",
    "Abrir uma reclamação": "Abrir un reclamo",
    "Confirmar receção do pagamento": "Confirmar recepción del pago",
    "Comprovativo de transferência (obrigatório)": "Comprobante de transferencia (obligatorio)",
    "Imagem ou PDF da transferência": "Imagen o PDF de la transferencia",
    "Confirmar transferência": "Confirmar transferencia",
    "{description} Tempo restante: {countdown}.": "{description} Tiempo restante: {countdown}.",
    "Comprovativo de pagamento": "Comprobante de pago",
    "Declarar pagamento": "Declarar pago",
    "Prazo: {date}": "Plazo: {date}",
    "Comprovativo da empresa": "Comprobante de la empresa",
    "Em espera": "En espera",
    "Cancelar transferência": "Cancelar transferencia",
    "Ação necessária": "Acción requerida",
    "A enviar…": "Subiendo…",
    "Nenhuma ação necessária de momento.": "No se requiere ninguna acción por ahora.",
    "A sua declaração foi enviada. A empresa verifica a receção do pagamento.": "Tu declaración fue enviada. La empresa está verificando la recepción del pago.",
    "A empresa prepara a transferência. Será notificado assim que for confirmada.": "La empresa está preparando la transferencia. Te notificaremos cuando se confirme.",
    "A transferência foi confirmada. Em breve poderá declarar a receção dos fundos.": "La transferencia fue confirmada. Pronto podrás declarar la recepción de los fondos.",
    "Transferência concluída.": "Transferencia completada.",
    "A aguardar a declaração de pagamento do cliente.": "Esperando la declaración de pago del cliente.",
    "Transferência confirmada. A aguardar a declaração de receção.": "Transferencia confirmada. Esperando la declaración de recepción.",
    "Transferência encerrada.": "Transferencia cerrada.",
    "Verifique a sua conta e valide esta etapa para avançar para o envio.": "Verifica tu cuenta y confirma este paso para pasar al envío.",
    "Adicione o comprovativo da transferência para o destinatário e valide.": "Agrega el comprobante de la transferencia al destinatario y confirma.",
    "Declarar o seu pagamento": "Declara tu pago",
    "Adicione um comprovativo e confirme a declaração.": "Agrega un comprobante y confirma tu declaración.",
    "Declarar a receção dos fundos": "Declarar la recepción de los fondos",
    "Confirme que o destinatário recebeu o montante.": "Confirma que el destinatario recibió el monto.",
    "Criar uma transferência": "Crear una transferencia",
    "Escolha uma empresa validada. Ela receberá a operação e acompanhará o tratamento até à validação.": "Elige una empresa verificada. Recibirá la operación y la gestionará hasta la validación.",
    "Cambistas": "Cambistas",
    "A sua empresa de transferências está ativa": "Tu empresa de transferencias está activa",
    "A sua empresa está em validação": "Tu empresa está en validación",
    "{name} é visível para os outros membros nesta lista. Como proprietário, não a pode usar para criar uma transferência — é a sua atividade de receção, não um parceiro a selecionar.": "{name} es visible para los demás miembros en esta lista. Como propietario, no puedes usarla para crear una transferencia: es tu actividad de recepción, no un socio a seleccionar.",
    "{name} ainda não aparece aqui: o MOXT deve primeiro validar o seu perfil. Depois do estado «Verificado», os membros poderão escolhê-lo como parceiro de transferência.": "{name} aún no aparece aquí: MOXT debe primero validar tu perfil. Cuando el estado sea «Verificado», los miembros podrán elegirte como socio de transferencia.",
    "Sentido da transferência": "Sentido de la transferencia",
    "Selecionado": "Seleccionado",
    "Montante a enviar em {currency}": "Monto a enviar en {currency}",
    "Mín. {amount}": "Mín. {amount}",
    "Mínimo": "Mínimo",
    "Utilizado este mês: {amount}.": "Usado este mes: {amount}.",
    "Conta verificada — limite aumentado.": "Cuenta verificada — límite aumentado.",
    "Escolher um parceiro": "Elegir un socio",
    "Todos os cambistas": "Todos los cambistas",
    "Nenhum parceiro no seu país": "Ningún socio en tu país",
    "Apenas os cambistas de {flag} o seu país de origem são mostrados para garantir as moedas corretas.": "Solo se muestran los cambistas de {flag} tu país de origen para garantizar las monedas correctas.",
    "A sua empresa recebe transferências de outros membros.": "Tu empresa recibe transferencias de otros miembros.",
    "A sua empresa": "Tu empresa",
    "Apenas receção": "Solo recepción",
    "Espaço pro": "Espacio pro",
    "taxas": "comisiones",
    "Estimativa da transferência": "Estimación de la transferencia",
    "Paga": "Pagas",
    "O destinatário recebe ~": "El destinatario recibe ~",
    "Montante enviado": "Monto enviado",
    "Prazo estimado": "Plazo estimado",
    "Taxa indicativa · fonte {source} · {date} · margem {margin}%. O montante recebido pode variar ligeiramente.": "Tipo indicativo · fuente {source} · {date} · margen {margin}%. El monto recibido puede variar ligeramente.",
    "Introduza um montante para ver a estimativa.": "Ingresa un monto para ver la estimación.",
    "2. Remetente": "2. Remitente",
    "3. Destinatário": "3. Destinatario",
    "Resumo e confirmação": "Resumen y confirmación",
    "Empresa parceira": "Empresa socia",
    "Confirmo estas informações e autorizo a sua transmissão à empresa selecionada para o tratamento desta operação.": "Confirmo esta información y autorizo su transmisión a la empresa seleccionada para procesar esta operación.",
    "Criar e enviar a transferência": "Crear y enviar la transferencia",
    "Perfis favoritos": "Perfiles favoritos",
    "Nome": "Nombre",
    "Apelido": "Apellido",
    "Rede ou banco": "Red o banco",
    "Nenhum perfil favorito para este país. Preencha manualmente.": "Ningún perfil favorito para este país. Completa los datos manualmente.",
    "Escolha uma empresa disponível.": "Elige una empresa disponible.",
    "Não pode utilizar a sua própria empresa.": "No puedes usar tu propia empresa.",
    "Esta empresa ainda não configurou a conta de receção para este sentido de transferência.": "Esta empresa aún no ha configurado la cuenta de recepción para este sentido de transferencia.",
    "A sua empresa recebe transferências de outros membros. Escolha outro parceiro.": "Tu empresa recibe transferencias de otros miembros. Elige otro socio.",
    "Detalhe da transferência": "Detalle de la transferencia",
    "{direction} · criada em {date}": "{direction} · creada el {date}",
    "Transferência {id} · {contact}": "Transferencia {id} · {contact}",
    "Comprovativo adicionado": "Comprobante agregado",
    "O comprovativo de pagamento está pronto.": "El comprobante de pago está listo.",
    "O comprovativo de transferência está pronto.": "El comprobante de transferencia está listo.",
    "Envio impossível": "Carga fallida",
    "Criação": "Creación",
    "Parceiro": "Socio",
    "Acompanhamento": "Seguimiento",
    "Pagamento": "Pago",
    "Detalhes": "Detalles",
    "A empresa irá verificar a receção do seu pagamento.": "La empresa verificará la recepción de tu pago.",
    "A receção do pagamento já foi confirmada ou o estado mudou.": "La recepción del pago ya fue confirmada o el estado cambió.",
    "Adicione um comprovativo de transferência antes de confirmar.": "Agrega un comprobante de transferencia antes de confirmar.",
    "Receção confirmada": "Recepción confirmada",
    "Transferência confirmada": "Transferencia confirmada",
    "Passe à etapa seguinte: comprovativo e confirmação da transferência.": "Pasa al siguiente paso: comprobante y confirmación de la transferencia.",
    "O cliente pode declarar a receção dos fundos.": "El cliente puede declarar la recepción de los fondos.",
    "Esta transferência está {status}. Não é possível qualquer outra ação.": "Esta transferencia está {status}. No es posible ninguna otra acción.",
    "Os dados": "Los datos",
    "A referência": "La referencia",
    "Copiar {label}": "Copiar {label}",
    "Informações da operação": "Información de la operación",
    "Referência": "Referencia",
    "Montante recebido (estimado)": "Monto recibido (estimado)",
    "Modo": "Modo",
    "Transferência assistida MOXT": "Transferencia asistida MOXT",
    "Proteção da operação": "Protección de la operación",
    "Verifique a identidade do cambista e os dados de pagamento.": "Verifica la identidad del cambista y los datos de pago.",
    "Guarde os comprovativos de pagamento no MOXT.": "Guarda tus comprobantes de pago en MOXT.",
    "O recibo descarregável serve de referência para o acompanhamento da operação.": "El recibo descargable sirve de referencia para el seguimiento de la operación.",
    "Reclamação": "Reclamo",
    "Motivo da reclamação": "Motivo del reclamo",
    "A nossa equipa analisa cada reclamação e contacta-o em 48h através da mensagens MOXT.": "Nuestro equipo revisa cada reclamo y te contacta en 48 h a través de tu mensajería MOXT.",
    "Enviar reclamação": "Enviar reclamo",
    "Cancelar esta transferência?": "¿Cancelar esta transferencia?",
    "Esta ação é definitiva. A transferência será marcada como cancelada e não poderá ser retomada.": "Esta acción es definitiva. La transferencia se marcará como cancelada y no se podrá reanudar.",
    "Recebido (estimado)": "Recibido (estimado)",
    "Tratado por {name}": "Procesado por {name}",
    "Resumo financeiro": "Resumen financiero",
    "Taxa aplicada": "Tipo aplicado",
    "Fonte da taxa": "Fuente del tipo",
    "Taxa local": "Tipo local",
    "Parceiro histórico": "Socio histórico",
    "Dados de pagamento": "Datos de pago",
    "A confirmar com a empresa": "Por confirmar con la empresa",
    "País de receção": "País de recepción",
    "Copiar referência": "Copiar referencia",
    "PDF": "PDF",
    "Imagem": "Imagen",
    "Partilhar": "Compartir",
    "Participantes": "Participantes",
    "Cronologia": "Cronología",
    "Transferência não encontrada": "Transferencia no encontrada",
    "Ações de administrador": "Acciones de administrador",
    "Intervenção direta a partir da ficha de transferência.": "Intervención directa desde la ficha de transferencia.",
    "Passar para {status}": "Avanzar a {status}",
    "Forçar cancelamento": "Forzar cancelación",
    "Pague em segurança": "Paga con seguridad",
    "Nunca pague fora do MOXT, guarde todos os comprovativos de pagamento e verifique os dados do parceiro antes de qualquer transação.": "Nunca pagues fuera de MOXT, guarda todos tus comprobantes de pago y verifica los datos del socio antes de cualquier transacción.",
    "A receção foi declarada e a empresa confirmou a transferência com comprovativo. Só é possível uma reclamação.": "La recepción fue declarada y la empresa confirmó la transferencia con comprobante. Solo es posible un reclamo.",
    "Efetue o pagamento antes de {date}. Tempo restante: {countdown}.": "Realiza el pago antes del {date}. Tiempo restante: {countdown}.",
    "Declaração recebida": "Declaración recibida",
    "Foi registada uma declaração de pagamento. Verifique a sua conta e valide a receção.": "Se registró una declaración de pago. Verifica tu cuenta y confirma la recepción.",
    "Vista global": "Vista general",
    "A sua vez": "Tu turno",
    "Ações": "Acciones",
    "Cada ação é única e a próxima etapa depende do estado atual da operação.": "Cada acción es única y el siguiente paso depende del estado actual de la operación.",
    "Clique para adicionar uma imagem ou PDF": "Haz clic para agregar una imagen o PDF",
    "Receção declarada": "Recepción declarada",
    "Em {date}": "El {date}",
    "Nenhuma ação disponível.": "Ninguna acción disponible.",
    # P2P
    "Trocas comunitárias": "Intercambios comunitarios",
    "Trocas P2P": "Intercambios P2P",
    "Publique uma oferta após verificar a sua conta, ou aceite uma oferta existente.": "Publica una oferta después de verificar tu cuenta, o acepta una oferta existente.",
    "Ofertas ativas": "Ofertas activas",
    "Propor uma oferta": "Proponer una oferta",
    "Troque em segurança": "Intercambia con seguridad",
    "Nunca pague fora do MOXT, guarde todos os comprovativos de pagamento e verifique a identidade do interlocutor antes de qualquer transação.": "Nunca pagues fuera de MOXT, guarda todos tus comprobantes de pago y verifica la identidad de tu contraparte antes de cualquier transacción.",
    "Moeda, método, utilizador ou condição...": "Moneda, método, usuario o condición...",
    "Moeda proposta": "Moneda ofrecida",
    "Moeda pretendida": "Moneda solicitada",
    "Todas": "Todas",
    "Arquivos": "Archivos",
    "Ativa": "Activa",
    "Arquivada": "Archivada",
    "Empresa": "Empresa",
    "Particular": "Particular",
    "{amount} para {currency}": "{amount} a {currency}",
    "Taxa {rate}": "Tipo {rate}",
    "Taxas estimadas": "Comisiones estimadas",
    "Aceitar": "Aceptar",
    "Detalhe": "Detalle",
    "Nenhuma oferta P2P ativa": "Ninguna oferta P2P activa",
    "Nenhum arquivo": "Ningún archivo",
    "Proponha a primeira oferta ou ajuste os filtros.": "Propón la primera oferta o ajusta tus filtros.",
    "As ofertas aceites ou encerradas aparecerão aqui.": "Las ofertas aceptadas o cerradas aparecerán aquí.",
    "As minhas transações recentes": "Mis transacciones recientes",
    "{seller} para {buyer}": "{seller} a {buyer}",
    "Oferta P2P não encontrada": "Oferta P2P no encontrada",
    "Oferta publicada por {name}": "Oferta publicada por {name}",
    "Conversão": "Conversión",
    "Proposto por": "Propuesto por",
    "Condições da oferta": "Condiciones de la oferta",
    "Montante proposto": "Monto propuesto",
    "Taxa": "Tipo",
    "Contactar ou aceitar": "Contactar o aceptar",
    "{from} para {to}": "{from} a {to}",
    "Aceitar a oferta": "Aceptar la oferta",
    "A aceitação cria uma transação local. Nenhum pagamento real é acionado.": "Aceptar crea una transacción local. No se dispara ningún pago real.",
    "Detalhes da troca": "Detalles del intercambio",
    "Montante disponível": "Monto disponible",
    "Moeda pedida": "Moneda pedida",
    "Taxa proposta": "Tipo propuesto",
    "Perfil": "Perfil",
    "Segurança P2P": "Seguridad P2P",
    "Esta operação é tratada via MOXT. Mantenha-se vigilante e guarde os comprovativos.": "Esta operación se gestiona vía MOXT. Mantente atento y guarda tus comprobantes.",
    "Guarde os comprovativos na conversa.": "Guarda los comprobantes en la conversación.",
    "Confirme os montantes antes de qualquer entrega real.": "Confirma los montos antes de cualquier entrega real.",
    "Criada": "Creada",
    "Pagamento em curso": "Pago en curso",
    "Concluída": "Completada",
    "Cancelada": "Cancelada",
    "Transação não encontrada.": "Transacción no encontrada.",
    "Transação P2P": "Transacción P2P",
    "Moeda recebida": "Moneda recibida",
    "Concluir": "Completar",
    "Cancelar": "Cancelar",
    "Adicionar comprovativo": "Agregar comprobante",
    "Transação P2P {id}": "Transacción P2P {id}",
    "Guardar recibo": "Guardar recibo",
    "Litígio": "Disputa",
    "Litígio {status}: {reason}": "Disputa {status}: {reason}",
    "Descreva o problema com precisão": "Describe el problema con precisión",
    "Abrir um litígio": "Abrir una disputa",
    "Avaliar a transação": "Calificar la transacción",
    "O seu comentário": "Tu comentario",
    "Guardar avaliação": "Guardar calificación",
    "Moedas": "Monedas",
    "Modalidades": "Modalidades",
    "P2P": "P2P",
    "Propor uma oferta P2P": "Proponer una oferta P2P",
    "Par de moedas": "Par de monedas",
    "As suas trocas P2P estão limitadas às moedas do seu perfil: {currencies}.": "Tus intercambios P2P están limitados a las monedas de tu perfil: {currencies}.",
    "Proponho": "Ofrezco",
    "Procuro": "Busco",
    "Nunca pague fora do MOXT e verifique a identidade do interlocutor antes de qualquer transação.": "Nunca pagues fuera de MOXT y verifica la identidad de tu contraparte antes de cualquier transacción.",
    "Montante e taxa": "Monto y tipo",
    "Limite atual: {amount}": "Límite actual: {amount}",
    "Montante ({currency})": "Monto ({currency})",
    "Taxa proposta ({from} → {to})": "Tipo propuesto ({from} → {to})",
    "Taxas estimadas: {amount}": "Comisiones estimadas: {amount}",
    "Modalidades da troca": "Modalidades del intercambio",
    "Mobile Money, banco…": "Mobile Money, banco…",
    "Condições (opcional)": "Condiciones (opcional)",
    "Horários, prazos, detalhes…": "Horarios, plazos, detalles…",
    "Publicar a oferta": "Publicar oferta",
    "Oferta P2P publicada": "Oferta P2P publicada",
    "A sua oferta está visível nas trocas P2P.": "Tu oferta es visible en los intercambios P2P.",
    # Favorites
    "Conta": "Cuenta",
    "Os meus favoritos": "Mis favoritos",
    "Anúncios, encomendas, empregos e outros conteúdos guardados — organizados por categoria.": "Anuncios, pedidos, empleos y otros contenidos guardados — organizados por categoría.",
    "Itens": "Elementos",
    "Perfil de transferência": "Perfil de transferencia",
    "Sem conteúdos favoritos": "Sin contenidos favoritos",
    "Guarde anúncios, encomendas, empregos ou empresas a partir das respetivas fichas.": "Guarda anuncios, pedidos, empleos o empresas desde sus fichas.",
    "Explorar o marketplace": "Explorar el marketplace",
    "Todos": "Todos",
    "Anúncios": "Anuncios",
    "Encomendas": "Pedidos",
    "Empregos": "Empleos",
    "Outros": "Otros",
    "{count} item": "{count} elemento",
    "{count} itens": "{count} elementos",
    "Remover": "Quitar",
    "Abrir": "Abrir",
    "Evento": "Evento",
    "Grátis": "Gratis",
    "Sob orçamento": "Bajo presupuesto",
    "Guardado": "Guardado",
    "Adicionar aos favoritos": "Agregar a favoritos",
    "Perfis de transferência": "Perfiles de transferencia",
    "Contactos reutilizáveis para preencher as suas transferências mais depressa.": "Contactos reutilizables para completar tus transferencias más rápido.",
    "Adicionar": "Agregar",
    "Sem perfis de transferência": "Sin perfiles de transferencia",
    "Adicione os seus contactos habituais para poupar tempo.": "Agrega tus contactos habituales para ahorrar tiempo.",
    "Editar perfil": "Editar perfil",
    "Novo perfil": "Nuevo perfil",
    "Rede móvel": "Red móvil",
    "Guardar alterações": "Guardar cambios",
    "Guardar perfil": "Guardar perfil",
    "O nome é obrigatório.": "El nombre es obligatorio.",
    "O apelido é obrigatório.": "El apellido es obligatorio.",
    "O número é obrigatório.": "El número de teléfono es obligatorio.",
    "Rede ou banco é obrigatório.": "La red o el banco es obligatorio.",
    # Receipts
    "Finanças": "Finanzas",
    "Recibos": "Recibos",
    "Comprovativos das suas operações registadas no MOXT.": "Comprobantes de tus operaciones registradas en MOXT.",
    "Recibo": "Recibo",
    "Processamento": "Procesamiento",
    "Recibo PDF": "Recibo PDF",
    "Recibo imagem": "Recibo imagen",
    "Nenhum recibo guardado": "Ningún recibo guardado",
    "MOXT — RECIBO": "MOXT — RECIBO",
    "Assunto: {title}": "Asunto: {title}",
    "Montante: {amount}": "Monto: {amount}",
    "não definido": "no definido",
    "Guarde este documento como comprovativo da sua operação.": "Guarda este documento como comprobante de tu operación.",
    # Notifications
    "Alertas": "Alertas",
    "Notificações": "Notificaciones",
    "{count} notificação(ões) não lida(s).": "{count} notificación(es) no leída(s).",
    "Marcar todas como lidas": "Marcar todas como leídas",
    "Urgente": "Urgente",
    "Normal": "Normal",
    "Baixa": "Baja",
    "Lida": "Leída",
    "Nova": "Nueva",
    "Abrir conversa": "Abrir conversación",
    "Marcar como lida": "Marcar como leída",
    "Arquivar": "Archivar",
    "Sem notificações.": "Sin notificaciones.",
    # Shared short tokens already covered above; keep EN-identical safe terms
    "Calculateur": "Calculadora",
    "History": "Historial",
}


WORD_MAP = [
    (r"\btransferências\b", "transferencias"),
    (r"\bTransferências\b", "Transferencias"),
    (r"\btransferência\b", "transferencia"),
    (r"\bTransferência\b", "Transferencia"),
    (r"\bpagamento\b", "pago"),
    (r"\bPagamento\b", "Pago"),
    (r"\bcomprovativo\b", "comprobante"),
    (r"\bComprovativo\b", "Comprobante"),
    (r"\bcomprovativos\b", "comprobantes"),
    (r"\bComprovativos\b", "Comprobantes"),
    (r"\breceção\b", "recepción"),
    (r"\bReceção\b", "Recepción"),
    (r"\bmontante\b", "monto"),
    (r"\bMontante\b", "Monto"),
    (r"\btaxas\b", "comisiones"),
    (r"\bTaxas\b", "Comisiones"),
    (r"\bparceiro\b", "socio"),
    (r"\bParceiro\b", "Socio"),
    (r"\bdestinatário\b", "destinatario"),
    (r"\bDestinatário\b", "Destinatario"),
    (r"\bremetente\b", "remitente"),
    (r"\bRemetente\b", "Remitente"),
    (r"\boperação\b", "operación"),
    (r"\bOperação\b", "Operación"),
    (r"\boperações\b", "operaciones"),
    (r"\breclamação\b", "reclamo"),
    (r"\bReclamação\b", "Reclamo"),
    (r"\bnotificações\b", "notificaciones"),
    (r"\bNotificações\b", "Notificaciones"),
    (r"\butilizador\b", "usuario"),
    (r"\bfavoritos\b", "favoritos"),
    (r"\bhistórico\b", "historial"),
    (r"\bHistórico\b", "Historial"),
    (r"\bconcluído\b", "completado"),
    (r"\bConcluído\b", "Completado"),
    (r"\bpendente\b", "pendiente"),
    (r"\bPendente\b", "Pendiente"),
    (r"\bdisponível\b", "disponible"),
    (r"\bindisponível\b", "no disponible"),
    (r"\bselecionado\b", "seleccionado"),
    (r"\bSelecionado\b", "Seleccionado"),
    (r"\bvalidação\b", "validación"),
    (r"\bValidação\b", "Validación"),
    (r"\bconfirmação\b", "confirmación"),
    (r"\bConfirmação\b", "Confirmación"),
    (r"\bdeclaração\b", "declaración"),
    (r"\bDeclaração\b", "Declaración"),
    (r"\bestimativa\b", "estimación"),
    (r"\bEstimativa\b", "Estimación"),
    (r"\bmargem\b", "margen"),
    (r"\breferência\b", "referencia"),
    (r"\bReferência\b", "Referencia"),
    (r"\bdireção\b", "dirección"),
    (r"\bDireção\b", "Dirección"),
    (r"\bsentido\b", "sentido"),
    (r"\bempresa\b", "empresa"),
    (r"\bEmpresa\b", "Empresa"),
    (r"\bcambista\b", "cambista"),
    (r"\bCambista\b", "Cambista"),
    (r"\bcambistas\b", "cambistas"),
    (r"\boferta\b", "oferta"),
    (r"\bofertas\b", "ofertas"),
    (r"\bmoeda\b", "moneda"),
    (r"\bMoeda\b", "Moneda"),
    (r"\bmoedas\b", "monedas"),
    (r"\btroca\b", "intercambio"),
    (r"\btrocas\b", "intercambios"),
    (r"\bTrocas\b", "Intercambios"),
    (r"\blitígio\b", "disputa"),
    (r"\bLitígio\b", "Disputa"),
    (r"\banúncios\b", "anuncios"),
    (r"\bAnúncios\b", "Anuncios"),
    (r"\bencomendas\b", "pedidos"),
    (r"\bEncomendas\b", "Pedidos"),
    (r"\bempregos\b", "empleos"),
    (r"\bEmpregos\b", "Empleos"),
    (r"\bperfil\b", "perfil"),
    (r"\bperfis\b", "perfiles"),
    (r"\bPerfis\b", "Perfiles"),
    (r"\bcontacto\b", "contacto"),
    (r"\bcontactos\b", "contactos"),
    (r"\btelefone\b", "teléfono"),
    (r"\bTelefone\b", "Teléfono"),
    (r"\bBenim\b", "Benín"),
    (r"\bRússia\b", "Rusia"),
    (r"\bÁfrica\b", "África"),
    (r"\bficheiros?\b", "archivo"),
    (r"\bficheiro\b", "archivo"),
    (r"\bdescarregar\b", "descargar"),
    (r"\bDescarregar\b", "Descargar"),
    (r"\bguardar\b", "guardar"),
    (r"\bGuardar\b", "Guardar"),
    (r"\bregistada\b", "registrada"),
    (r"\bregistado\b", "registrado"),
    (r"\bregistadas\b", "registradas"),
]

TU_MAP = [
    (r"\ba sua\b", "tu"),
    (r"\bA sua\b", "Tu"),
    (r"\bo seu\b", "tu"),
    (r"\bO seu\b", "Tu"),
    (r"\bas suas\b", "tus"),
    (r"\bAs suas\b", "Tus"),
    (r"\bos seus\b", "tus"),
    (r"\bOs seus\b", "Tus"),
    (r"\ba sua empresa\b", "tu empresa"),
    (r"\bA sua empresa\b", "Tu empresa"),
    (r"\bas minhas\b", "mis"),
    (r"\bAs minhas\b", "Mis"),
    (r"\bos meus\b", "mis"),
    (r"\bOs meus\b", "Mis"),
    (r"\bo meu\b", "mi"),
    (r"\ba minha\b", "mi"),
    (r"\bnão pode\b", "no puedes"),
    (r"\bNão pode\b", "No puedes"),
    (r"\bpode\b", "puedes"),
    (r"\bPode\b", "Puedes"),
    (r"\bescolha\b", "elige"),
    (r"\bEscolha\b", "Elige"),
    (r"\badicione\b", "agrega"),
    (r"\bAdicione\b", "Agrega"),
    (r"\bconfirme\b", "confirma"),
    (r"\bConfirme\b", "Confirma"),
    (r"\bverifique\b", "verifica"),
    (r"\bVerifique\b", "Verifica"),
    (r"\bdeclare\b", "declara"),
    (r"\bDeclare\b", "Declara"),
    (r"\bcrie\b", "crea"),
    (r"\bCrie\b", "Crea"),
    (r"\bintroduza\b", "ingresa"),
    (r"\bIntroduza\b", "Ingresa"),
    (r"\butilize\b", "usa"),
    (r"\bUtilize\b", "Usa"),
    (r"\bguarde\b", "guarda"),
    (r"\bGuarde\b", "Guarda"),
    (r"\bnunca pague\b", "nunca pagues"),
    (r"\bNunca pague\b", "Nunca pagues"),
    (r"\bpague\b", "paga"),
    (r"\bPague\b", "Paga"),
    (r"\befetue\b", "realiza"),
    (r"\bEfetue\b", "Realiza"),
    (r"\bmarque\b", "marca"),
    (r"\babra\b", "abre"),
    (r"\bAbra\b", "Abre"),
    (r"\bproponha\b", "propón"),
    (r"\bProponha\b", "Propón"),
    (r"\baceite\b", "acepta"),
    (r"\bpublique\b", "publica"),
    (r"\bPublique\b", "Publica"),
    (r"\bserá notificado\b", "te notificaremos"),
    (r"\bSerá notificado\b", "Te notificaremos"),
    (r"\bcontacta-o\b", "te contacta"),
    (r"\bpreencha\b", "completa"),
    (r"\bPreencha\b", "Completa"),
]


def protect_placeholders(text: str) -> tuple[str, list[str]]:
    values: list[str] = []

    def repl(match: re.Match[str]) -> str:
        values.append(match.group(0))
        return f"ZXPH{len(values) - 1}ZX"

    return re.sub(r"\{[^{}]+\}", repl, text), values


def restore_placeholders(text: str, values: list[str]) -> str:
    for index, value in enumerate(values):
        text = text.replace(f"ZXPH{index}ZX", value)
    return text


def fallback_translate(text: str) -> str:
    masked, values = protect_placeholders(text)
    out = masked
    for pattern, repl in WORD_MAP + TU_MAP:
        out = re.sub(pattern, repl, out)
    # Orthography tweaks common PT→ES
    out = out.replace("ção", "ción").replace("ções", "ciones")
    out = out.replace("são", "sión").replace("sões", "siones")
    out = out.replace("ância", "ancia").replace("ência", "encia")
    out = out.replace("ável", "able").replace("ível", "ible")
    out = out.replace("nh", "ñ")  # careful: can over-replace; fix known words below
    # undo bad ñ replacements
    for bad, good in [
        ("coñfirma", "confirma"),
        ("iñforma", "informa"),
        ("mañualmente", "manualmente"),
        ("oñline", "online"),
        ("teñha", "tenga"),
        ("señha", "contraseña"),
        ("Ñenhuma", "Ninguna"),
        ("ñenhuma", "ninguna"),
        ("ñenhum", "ningún"),
        ("Ñenhum", "Ningún"),
        ("desigñ", "design"),
        ("siñgle", "single"),
    ]:
        out = out.replace(bad, good)
    return restore_placeholders(out, values)


def translate_row(row: dict) -> str:
    source = row.get("pt") or row.get("fr") or row["en"]
    if source in OVERRIDES:
        return OVERRIDES[source]
    # Prefer EN override lookup when pt missing unique phrasing
    if row["en"] in OVERRIDES:
        return OVERRIDES[row["en"]]
    translated = fallback_translate(source)
    # Preserve MOXT / P2P exactly
    translated = translated.replace("Moxt", "MOXT")
    return translated


def main() -> None:
    rows = json.loads(SOURCE.read_text(encoding="utf-8"))["rows"]
    translations: dict[str, str] = {}
    for row in rows:
        translations[row["k"]] = translate_row(row)

    DESTINATION.parent.mkdir(parents=True, exist_ok=True)
    DESTINATION.write_text(
        json.dumps({"translations": translations}, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
        newline="\n",
    )

    # Validation
    missing = [r["k"] for r in rows if r["k"] not in translations]
    placeholder_issues = []
    for row in rows:
        src = row.get("pt") or row.get("fr") or row["en"]
        src_ph = re.findall(r"\{[^{}]+\}", src)
        dst_ph = re.findall(r"\{[^{}]+\}", translations[row["k"]])
        if src_ph != dst_ph:
            placeholder_issues.append((row["k"], src_ph, dst_ph))
    still_ptish = [
        k
        for k, v in translations.items()
        if any(tok in v for tok in ("ç", "ões", "ção", "ão ", "ã", "você", "utilizador", "ficheiro", "receção", "comprovativo"))
    ]
    print(f"Wrote {len(translations)} translations")
    print(f"missing={len(missing)} placeholder_issues={len(placeholder_issues)} ptish={len(still_ptish)}")
    if placeholder_issues[:5]:
        print("placeholder sample:", placeholder_issues[:5])
    if still_ptish[:20]:
        print("ptish sample:", still_ptish[:20])


if __name__ == "__main__":
    main()
